wso2/docs-ei

reference/ei_config_catalog.md
To create the 'reference' folder and the config catalog for the docs.
=> Create ei_config_catalog.md file

en/docs/References/ei_config_catalog.md
The config catalog for WSO2 EI is moved to the 'Reference' folder.
=> creating the ei_config_catalog.md file

en/docs/References/ei_config_catalog.md
Updated config catalog for WSO2 EI.
=> Updated config catalog for ei

en/docs/References/ei_config_catalog.md
=> Revert "Updated config catalog for ei"

en/micro-integrator/docs/references/ei_config_catalog.md
Updating the latest config catalog changes for EI.
=> Updated config catalog

en/micro-integrator/docs/setup/db/setting-up-MySQL.md
First draft of the 'creating a MySql db' doc.
=> Creating the mysql db doc.

en/micro-integrator/mkdocs.yml
Updating mkdocs.yml file with navigation changes.
=> Updating mkdocs.yml file.

en/micro-integrator/docs/setup/backup_recovery.md, en/micro-integrator/docs/setup/deployment_checklist.md, en/micro-integrator/docs/setup/deployment_synchronization.md, en/micro-integrator/docs/setup/install_in_docker.md, en/micro-integrator/docs/setup/install_in_kubernetes.md, en/micro-integrator/docs/setup/install_in_vm.md, en/micro-integrator/docs/setup/network_os_performance.md, en/micro-integrator/docs/setup/registry_mounting.md, en/micro-integrator/docs/setup/setting_up_jdbc_userstore.md, en/micro-integrator/docs/setup/setting_up_lb.md, en/micro-integrator/docs/setup/setting_up_ro_ldap.md, en/micro-integrator/docs/setup/setting_up_rw_ad.md, en/micro-integrator/docs/setup/setting_up_rw_ldap.md, en/micro-integrator/docs/setup/troubleshooting_deployment.md, en/micro-integrator/docs/setup/tuning_db_performance.md, en/micro-integrator/docs/setup/upgrading.md
Updating docs (first draft) of the configuration catalog.
=> Updating files for of the deployment guide.

en/micro-integrator/docs/setup/deploying_wso2_ei.md
The deployment/clustering doc.
=> Creating the deployment guide.

en/micro-integrator/mkdocs.yml
Updated some syntax errors in the yml file.
=> Updated reference section of the mkdocs.yml file.

en/micro-integrator/docs/overview/architecture.md, en/micro-integrator/docs/quick-start-guide/quick-start-guide.md, en/micro-integrator/mkdocs.yml
updated the yml, overview, and qsg.
=> Updated yml, overview, and qsg

en/streaming-integrator/docs/admin/configuring.md, en/streaming-integrator/docs/concepts.md, en/streaming-integrator/docs/examples/change_data_capturing_for_mssql.md, en/streaming-integrator/docs/overview/about_this_release.md, en/streaming-integrator/docs/overview/architecture.md, en/streaming-integrator/docs/overview/overview.md
=> Add the Streaming Integrator directory structure.

en/streaming-integrator/docs/admin/adding-third-party-non-osgi-libraries.md, en/streaming-integrator/docs/admin/configure-si-profile.md, en/streaming-integrator/docs/admin/configuring-system-parameters-for-siddhi-connectors.md, en/streaming-integrator/docs/admin/download-and-install-connectors.md, en/streaming-integrator/docs/admin/general-data-protection-regulations.md, en/streaming-integrator/docs/admin/monitoring-the-streaming-integrator.md, en/streaming-integrator/docs/admin/protecting-sensitive-data-via-the secure-vault.md, en/streaming-integrator/docs/admin/supporting-different-transports.md, en/streaming-integrator/docs/admin/user-management.md, en/streaming-integrator/docs/admin/working-with-business-rules.md, en/streaming-integrator/docs/admin/writing-custom-siddhi-connectors.md, en/streaming-integrator/docs/ref/configuring-default-ports.md, en/streaming-integrator/docs/ref/performance-analysis-results.md, en/streaming-integrator/docs/ref/si-profiles.md, en/streaming-integrator/docs/ref/si-rest-api-guide.md, en/streaming-integrator/docs/ref/working-with-data-providers.md, en/streaming-integrator/docs/setup/installing-si-using-ansible.md, en/streaming-integrator/docs/setup/installing-si-using-apt.md, en/streaming-integrator/docs/setup/installing-si-using-aws-cloud-formation.md, en/streaming-integrator/docs/setup/installing-si-using-brew.md, en/streaming-integrator/docs/setup/installing-si-using-docker-compose.md, en/streaming-integrator/docs/setup/installing-si-using-docker.md, en/streaming-integrator/docs/setup/installing-si-using-helm.md, en/streaming-integrator/docs/setup/installing-si-using-kubernetes.md, en/streaming-integrator/docs/setup/installing-si-using-puppet.md, en/streaming-integrator/docs/setup/installing-si-using-vagrant.md, en/streaming-integrator/docs/setup/installing-si-using-yum.md, en/streaming-integrator/docs/setup/setting-up-databases.md
=> Add SI Page Structure.

en/ballerina-integrator/docs/assets/css/theme.css, en/ballerina-integrator/docs/index.md, en/ballerina-integrator/docs/page-not-found.md, en/ballerina-integrator/mkdocs.yml, en/micro-integrator/docs/assets/css/theme.css, en/micro-integrator/docs/page-not-found.md, en/micro-integrator/mkdocs.yml, en/streaming-integrator/docs/assets/css/theme.css, en/streaming-integrator/docs/index.md, en/streaming-integrator/docs/page-not-found.md, en/streaming-integrator/mkdocs.yml
Add home page, 404 pages and color changes
=> Add home page, 404 pages and color changes

en/streaming-integrator/mkdocs.yml
Fix Streaming Integrator site details
=> Fix Streaming Integrator site details

en/streaming-integrator/docs/guides/cleansing-data.md, en/streaming-integrator/docs/guides/consuming_messages.md, en/streaming-integrator/docs/guides/correlating-events.md, en/streaming-integrator/docs/guides/enriching-data.md, en/streaming-integrator/docs/guides/storage-Integration.md, en/streaming-integrator/docs/guides/summarizing-data.md, en/streaming-integrator/docs/guides/transforming-data.md, en/streaming-integrator/docs/guides/triggering-integration-flows.md
This defines the basic structure for each guide in the Streaming Integrator/Guides section.
=> Define the subtopics in the Guides section

en/streaming-integrator/docs/guides/enriching-data.md
Review and modify headlines for new Stream Integrator guide on enriching data
=> Update headings for enrich guide

en/streaming-integrator/docs/guides/triggering-integration-flows.md
Update headings for triggering integration guide
=> Update headings for triggering integration guide

en/streaming-integrator/docs/examples/working-with-kafka.md
=> Correct URL formatting error in the Working with Kafka tutorial.

en/streaming-integrator/docs/guides/cleansing-data.md, en/streaming-integrator/docs/guides/enriching-data.md, en/streaming-integrator/docs/guides/summarizing-data.md, en/streaming-integrator/docs/guides/transforming-data.md, en/streaming-integrator/docs/guides/triggering-integration-flows.md
Update proposed guides with basic headings
=> Update basic structure for SI guides

en/streaming-integrator/docs/examples/cdc-for-mysql.md, en/streaming-integrator/docs/examples/working-with-kafka.md
Remove Stream Processor references and add formatting improvements.
=> Remove Stream Processor references and add formatting improvements

en/streaming-integrator/docs/examples/working-with-kafka.md
=> Review Working with Kafka example.

en/streaming-integrator/docs/examples/cdc-for-mysql.md
Fix Siddhi apps in CDC tutorial and other formatting improvements.
=> Fix Siddhi apps in CDC tutorial and other formatting improvements

en/streaming-integrator/docs/guides/consuming-messages.md
Complete the Consuming Messages guide
=> Add content to sections on Mapping in the Consuming Messages guide.

en/streaming-integrator/docs/guides/consuming-messages.md, en/streaming-integrator/docs/guides/publishing-data.md
=> Add content to sections related to Mapping in the Publishing Data guide.

en/streaming-integrator/docs/guides/publishing-data.md
=> Add content to sections on Mapping in the Publishing Data guide.

en/ballerina-integrator/docs/mkdocs-content/README.md, en/ballerina-integrator/docs/mkdocs-content/guides/database-integrations/mongo/mongo.md, en/ballerina-integrator/docs/mkdocs-content/guides/integration-patterns/integration-patterns.md, en/ballerina-integrator/docs/mkdocs-content/guides/messaging/activemq/activemq.md, en/ballerina-integrator/docs/mkdocs-content/guides/messaging/asynchronous-messaging/asynchronous-messaging.md, en/ballerina-integrator/docs/mkdocs-content/guides/messaging/message-broadcasting/message-broadcasting.md, en/ballerina-integrator/docs/mkdocs-content/guides/services/healthcare-service/healthcare-service.md, en/ballerina-integrator/docs/mkdocs-content/guides/testing/writing-tests-using-data-providers/writing-tests-using-data-providers.md, en/ballerina-integrator/docs/mkdocs-content/integration-tutorials/exposing-several-services-as-a-single-service/exposing-several-services-as-a-single-service.md, en/ballerina-integrator/docs/mkdocs-content/integration-tutorials/integration-tutorials.md, en/ballerina-integrator/docs/mkdocs-content/integration-tutorials/routing-requests-based-on-message-content/routing-requests-based-on-message-content.md, en/ballerina-integrator/docs/mkdocs-content/integration-tutorials/sending-a-simple-message-to-a-datasource/sending-a-simple-message-to-a-datasource.md, en/ballerina-integrator/docs/mkdocs-content/integration-tutorials/sending-a-simple-message-to-a-service/sending-a-simple-message-to-a-service.md, en/ballerina-integrator/docs/mkdocs-content/integration-tutorials/storing-and-forwarding-messages/storing-and-forwarding-messages.md, en/ballerina-integrator/docs/mkdocs-content/integration-tutorials/transforming-message-content/transforming-message-content.md, en/ballerina-integrator/docs/mkdocs-content/integration-tutorials/using-the-analytics-dashboard/using-the-analytics-dashboard.md, en/ballerina-integrator/docs/mkdocs-content/integration-tutorials/using-the-gmail-connector/using-the-gmail-connector.md
> Added guides and integration tutorials markdown files generated from the ballerina-integrator repo.
=> Add md files from ballerina-integrator repo

en/ballerina-integrator/docs/index.md, en/ballerina-integrator/theme/material/templates/home-page.html, en/micro-integrator/docs/index.md, en/micro-integrator/theme/material/templates/home-page.html, en/streaming-integrator/docs/index.md, en/streaming-integrator/theme/material/templates/home-page.html
Remove top nav bar from home page
=> Remove top nav bar from home page

en/micro-integrator/docs/references/config-catalog.md, en/micro-integrator/mkdocs.yml
Includes following:
- admin services removed from yml.
- configuration is updated with content
=> removing admin services docs from yaml

en/streaming-integrator/docs/guides/correlating-events.md
Update basic structure for SI guide on correlation. Here we have added pattern as a correlation mechanism
=> Update basic structure for SI guide on correlation

en/streaming-integrator/docs/guides/correlating-events.md, en/streaming-integrator/docs/guides/enriching-data.md
=> Complete the Enrich Data guide.

en/streaming-integrator/docs/guides/correlating-events.md
=> Add information about non-occurring events to the Correlating Data guide.

en/streaming-integrator/docs/examples/performing-real-time-etl-with-files.md
Add remote file processing example into `Performing Real-time ETL with Files` tutorial.
=> Add remote file processing example into 'Performing Real-time ETL with Files' tutorial

en/streaming-integrator/docs/guides/correlating-events.md, en/streaming-integrator/docs/guides/summarizing-data.md
=> Add content about Counting Patterns to the Correlating Events guide.

en/ballerina-integrator/mkdocs.yml
=> Update mkdocs.yml for Ballerina Integrator

en/ballerina-integrator/docs/develop/cicd.md, en/ballerina-integrator/docs/develop/using-modules.md, en/ballerina-integrator/docs/setup/deploy-on-kubernetes.md
=> Add new content

en/streaming-integrator/docs/guides/storage-Integration.md, en/streaming-integrator/docs/quick-start-guide/quick-start-guide-101.md, en/streaming-integrator/mkdocs.yml
=> Add Content to the Storage Integration Guide

en/streaming-integrator/docs/examples/siddhi-query-api.md
Add Siddhi Query API Tutorial.
=> Add Siddhi Query API Tutorial

en/streaming-integrator/mkdocs.yml
=> Move Guides above Examples.

en/ballerina-integrator/docs/getting-started/quick-start-guide.md
=> Update topic content

en/streaming-integrator/docs/examples/exposing-processed-data-as-api.md
=> Complete linguistic review for the API tutorial in Streaming Integrator.

en/streaming-integrator/docs/quick-start-guide/hello-world-with-mi.md, en/streaming-integrator/mkdocs.yml
=> Rename menu items for Streaming Integrator.

en/streaming-integrator/docs/quick-start-guide/getting-started-with-si.md, en/streaming-integrator/docs/quick-start-guide/hello-world-with-mi.md, en/streaming-integrator/mkdocs.yml
=> Rename "Examples" to "Tutorials" for the Streaming Integrator.

en/ballerina-integrator/docs/assets/js/theme.js, en/micro-integrator/docs/assets/js/theme.js, en/streaming-integrator/docs/assets/js/theme.js
=> Fix ballerina integrator dropdown link

en/streaming-integrator/docs/admin/monitoring-Stream-Processor.md, en/streaming-integrator/docs/admin/monitoring-the-streaming-integrator.md, en/streaming-integrator/docs/ref/hTTP-Status-Codes.md, en/streaming-integrator/docs/ref/si-rest-api-guide.md, en/streaming-integrator/mkdocs.yml
=> Add basic content to the Streaming Integrator REST API guide.

en/streaming-integrator/docs/setup/migrating-from-stream-processor.md
=> Add content to the Streaming Integrator Migration Guide.

en/streaming-integrator/docs/setup/migrating-from-stream-processor.md
=> Add corrections to the Streaming Integrator Migration Guide (after review).

en/streaming-integrator/docs/examples/working-with-kafka.md
=> Restructure the "Working with Kafka" tutorial

en/streaming-integrator/docs/examples/performing-real-time-etl-with-mysql.md
=> Restructure the "Performing Real-time ETL with MySQL" tutorial.

en/streaming-integrator/mkdocs.yml
=> Update the Streaming Integrator navigator.

en/streaming-integrator/docs/examples/performing-real-time-etl-with-files.md, en/streaming-integrator/docs/examples/performing-real-time-etl-with-mysql.md
=> Restructure and format the tutorials on performing ETL.

en/micro-integrator/docs/develop/injecting-parameters.md
Fixes: https://github.com/wso2/micro-integrator/issues/868
=> Fix https://github.com/wso2/micro-integrator/issues/868

en/micro-integrator/docs/use-cases/examples/rest_api_examples/introduction-rest-api.md
This is to add synapse namespace in to the sample API config
=> Add namespace in the sample config

en/micro-integrator/docs/references/mediators/forEach-Mediator.md
Native JSON support is introduced in foreach mediator. wso2/wso2-synapse#1377 Adhering to this, we should update the Foreach mediator documentation.
Related issue https://github.com/wso2/product-ei/issues/4367
=> Update docs on native JSON support for foreach mediator

en/micro-integrator/docs/use-cases/integration-use-cases.md
=> Update use cases

en/streaming-integrator/docs/quick-start-guide/hello-world-with-mi.md
$subject by removing class mediator and adding respond in inSeq
=> Fix hello-world-with-mi qsg

en/micro-integrator/docs/administer-and-observe/using-the-command-line-interface.md
Update the documentation related to CLI. 
Fixes: https://github.com/wso2/micro-integrator/issues/693
Fixes: https://github.com/wso2/micro-integrator/issues/918
=> Fix EI-693 Update CLI docs

en/micro-integrator/docs/use-cases/examples/using-scheduled-tasks.md
Update the samples of Using Scheduled Tasks doc
=> Update the samples of Using Scheduled Tasks doc

en/streaming-integrator/docs/ref/performance-analysis-results.md, en/streaming-integrator/docs/samples/PublishHTTPInJsonFormatWithCustomMapping.md, en/streaming-integrator/docs/samples/PublishHttpInXmlFormat.md, en/streaming-integrator/docs/samples/PublishHttpInXmlFormatWithCustomMapping.md
=> Format imported Streaming Integrator examples.

en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/file-inbound-endpoint.md, en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-hl7-protocol-auto-ack.md, en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-http-protocol.md, en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-https-protocol.md, en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-jms-protocol.md, en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-rabbitmq-protocol.md, en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/using-inbound-endpoints.md
This PR will contain doc changes for Inbound Endpoints.
=> Update Inbound Endpoint docs

en/micro-integrator/docs/use-cases/examples/registry_examples/Local-Registry-Entry-Definitions-Reusable-Endpoints-and-Sequences.md, en/micro-integrator/docs/use-cases/examples/template_examples/using-sequence-templates.md
- Split the given sample to its constituent parts
- Introduced a proxy instead of a main Sequence
- Changed the stockquote url to reflect new proxy
=> Modified Samples for 'Local Registry Entry Definitions' and 'Using Sequence Templates'

en/micro-integrator/docs/use-cases/examples/message_store_processor_examples/using-jdbc-message-store.md, en/micro-integrator/docs/use-cases/examples/using-scheduled-tasks.md
Fix doc samples Using a JDBC Message Store and Add synapse namespaces for the scheduled task sampes
=> Fix doc samples Using a JDBC Message Store

en/micro-integrator/docs/use-cases/examples/endpoint_examples/using-address-endpoints.md
This PR contains the doc changes in Address Endpoint doc under use-cases/examples/endpoint-address-endpoints.
=> Modify Address Endpoint doc

en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-mqtt-protocol.md
This PR will contain the doc changes in MQTT Inbound Endpoint doc.
=> Update MQTT Inbound Endpoint doc

en/ballerina-integrator/docs/assets/js/theme.js, en/micro-integrator/docs/assets/js/theme.js, en/streaming-integrator/docs/assets/js/theme.js
=> Fix broken link for BI docs

en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-mqtt-protocol.md, en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/using-secure-websocket-inbound.md
This PR will contain the doc changes in WebSocket Inbound Endpoint.
=> Update WebSocket Inbound Endpoint doc

en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/using-kafka-inbound-endpoints.md
Update Kafka Inbound Endpoint doc
=> Update Kafka inbound endpoint doc

en/streaming-integrator/docs/samples/AggregateDataIncrementally.md, en/streaming-integrator/docs/samples/CDCWithListeningMode.md, en/streaming-integrator/docs/samples/CDCWithPollingMode.md, en/streaming-integrator/docs/samples/CSVCustomMapping.md, en/streaming-integrator/docs/samples/CSVDefaultMapping.md, en/streaming-integrator/docs/samples/ClusTreeTestApp.md, en/streaming-integrator/docs/samples/DataPreprocessing.md, en/streaming-integrator/docs/samples/ExtremaBottomK.md, en/streaming-integrator/docs/samples/GCSSinkSample.md, en/streaming-integrator/docs/samples/GeoDistanceCalculation.md, en/streaming-integrator/docs/samples/GplNLPFindNameEntityType.md, en/streaming-integrator/docs/samples/KalmanFilterExecutionSample.md, en/streaming-integrator/docs/samples/MapExtensionSample.md, en/streaming-integrator/docs/samples/MarkovChainSample.md, en/streaming-integrator/docs/samples/PriorityExtensionSample.md, en/streaming-integrator/docs/samples/PublishEmailInTextFormat.md, en/streaming-integrator/docs/samples/PublishEmailInXmlFormat.md, en/streaming-integrator/docs/samples/PublishEventsToFile.md, en/streaming-integrator/docs/samples/PublishGooglePubSubMessagesInTextFormat.md, en/streaming-integrator/docs/samples/ReceiveGooglePubSubMessagesInTextFormat.md, en/streaming-integrator/docs/samples/execution-geo-sample.md
=> Fix SI samples

en/micro-integrator/docs/use-cases/tutorials/sending-a-simple-message-to-a-service.md
=> Update sending simple message to a service tutorial.

en/streaming-integrator/docs/setup/deploying-si-as-a-single-deployment.md
=> Add correct URL for state persistence link in SI single deployment

en/home-page/docs/assets/css/theme.css, en/home-page/docs/index.md
=> fix home page styles

en/micro-integrator/docs/setup/installation/install_in_kubernetes.md, en/micro-integrator/mkdocs.yml
> This PR will add the docs for running MI on kubernetes.
=> Add run on kubernetes guide

en/home-page/docs/assets/css/theme.css, en/home-page/docs/index.md
=> home page text changes

en/micro-integrator/docs/setup/installation/install_in_kubernetes.md
> This PR will fix the Kubernetes project creation link issue.
=> Fix link referring issue

en/micro-integrator/docs/setup/installation/run_in_docker.md, en/micro-integrator/mkdocs.yml
Update install-in-docker page to run-in-docker page
=> Update install-in-docker page

en/micro-integrator/docs/references/mediators/header-Mediator.md
Reverts wso2/docs-ei#676
This has to be merged to 7.0.0 branch
=> Revert "Update header mediator docs with jsonpath support"

en/micro-integrator/docs/use-cases/tutorials/storing-and-forwarding-messages.md
=> Fix Asynchronous Messaging tutorial

en/micro-integrator/docs/use-cases/tutorials/exposing-several-services-as-a-single-service.md, en/micro-integrator/docs/use-cases/tutorials/transforming-message-content.md
=> Fix doc issues

en/streaming-integrator/docs/examples/triggering-integrations-via-micro-integrator.md
=> Fix gRPC tutorial

en/micro-integrator/docs/develop/kubernetes_deployment.md
> Update Kubernetes deployment md file
=> Update Kubernetes deployment md file

en/micro-integrator/docs/develop/k8s-samples/content-based-routing.md
> Add content based routing k8s sample
=> Add content based routing k8s sample

en/micro-integrator/docs/setup/installation/run_in_docker.md
Remove unwanted port forwarding
=> Remove unwanted port forwarding

en/ballerina-integrator/mkdocs.yml, en/home-page/mkdocs.yml, en/micro-integrator/mkdocs.yml, en/streaming-integrator/mkdocs.yml
=> fix canonical URL

en/ballerina-integrator/mkdocs.yml, en/micro-integrator/mkdocs.yml, en/streaming-integrator/mkdocs.yml
=> Canonical fix

en/micro-integrator/docs/setup/installation/run_in_docker.md
> This PR will fix the docker tag versions mentioned in the doc.
=> Fix docker tag versions

en/micro-integrator/docs/setup/installation/install_in_vm.md
=> Update Installation VM

en/micro-integrator/docs/setup/installation/run_in_docker.md
> This PR wil fix docker tag versions in the example
=> Fix docker tag versions in example

en/ballerina-integrator/docs/assets/css/theme.css, en/ballerina-integrator/docs/index.md, en/home-page/docs/index.md, en/micro-integrator/docs/assets/css/theme.css, en/micro-integrator/docs/index.md, en/streaming-integrator/docs/assets/css/theme.css, en/streaming-integrator/docs/index.md
fix the home page styles on all sites with correct order
=> fix the home page styles on all sites with correct order

en/ballerina-integrator/docs/index.md, en/streaming-integrator/docs/index.md
=> Revert "7.0.0"

en/ballerina-integrator/docs/index.md, en/micro-integrator/docs/index.md, en/streaming-integrator/docs/index.md
=> fix relative paths

en/micro-integrator/docs/setup/brokers/configure-with-ActiveMQ.md, en/micro-integrator/docs/use-cases/tutorials/using-scheduled-tasks.md
Correct reference project name in using-scheduled-tasks.md
=> Correct reference project name

en/micro-integrator/docs/references/synapse-properties/data-services.md
=> Update odata endpoint

en/micro-integrator/docs/develop/creating-artifacts/creating-a-proxy-service.md, en/micro-integrator/docs/develop/creating-artifacts/creating-an-api.md
Update API and proxy creation pages.
=> Update API and proxy creation pages

en/micro-integrator/docs/references/synapse-properties/about-message-stores-processors.md
=> Fix broken links

en/micro-integrator/docs/use-cases/examples/file-processing/vfs-transport-examples.md
Updated broken VFS link in vfs-transport-examples.md.
=> Update broken VFS link in vfs-transport-examples.md

en/micro-integrator/docs/use-cases/examples/message_store_processor_examples/intro-message-stores-processors.md
Update Intro to message stores and processors
=> Update Intro to message stores and processors

en/micro-integrator/docs/develop/creating-artifacts/encrypting-synapse-passwords.md
> This PR includes documentation updates for the securevault.bat file.
=> Need to update securevault.bat file before run the securevault.bat file

en/micro-integrator/docs/setup/security/configuring_keystores.md
=> Fix broken hyperlink in Doc

en/micro-integrator/docs/references/best-Practices.md
=> Modify best practices doc

en/micro-integrator/docs/use-cases/examples/jms_examples/rabbitmq-examples.md
=> Updated rabbitmq-examples.md

en/ballerina-integrator/docs/assets/attach/SampleProxy/sample_proxy_1.wsdl, en/ballerina-integrator/docs/assets/attach/SampleProxy/sample_proxy_2.wsdl, en/micro-integrator/docs/use-cases/examples/endpoint_examples/using-address-endpoints.md, en/micro-integrator/docs/use-cases/examples/endpoint_examples/using-dynamic-recepient-list-endpoints-2.md, en/micro-integrator/docs/use-cases/examples/endpoint_examples/using-failover-endpoints.md, en/micro-integrator/docs/use-cases/examples/endpoint_examples/using-http-endpoints.md, en/micro-integrator/docs/use-cases/examples/endpoint_examples/using-loadbalancing-endpoints.md, en/micro-integrator/docs/use-cases/examples/endpoint_examples/using-wsdl-endpoints.md
- Changed some samples for the endpoints
- Added sample_proxy_1 and sample_proxy_2, however, this has to be linked for the user to be able to download them
=> Address Endpoint Example Changes

en/micro-integrator/docs/setup/brokers/configure-with-ActiveMQ.md, en/micro-integrator/docs/use-cases/examples/jms_examples/consume-produce-jms.md, en/micro-integrator/docs/use-cases/examples/jms_examples/consuming-jms.md, en/micro-integrator/docs/use-cases/examples/jms_examples/producing-jms.md
> This PR will add the suggested changes to jms transport docs
=> Add changes jms transport docs

en/micro-integrator/docs/use-cases/examples/data_integration/data-input-validator.md, en/micro-integrator/docs/use-cases/examples/data_integration/json-with-data-service.md, en/micro-integrator/docs/use-cases/examples/data_integration/nested-queries-in-data-service.md, en/micro-integrator/docs/use-cases/examples/data_integration/odata-service.md, en/micro-integrator/docs/use-cases/examples/data_integration/rdbms-data-service.md, en/micro-integrator/docs/use-cases/examples/data_integration/request-box.md
Modify data services examples doc
=> Modify data services examples doc

en/micro-integrator/docs/use-cases/tutorials/sap-integration.md
=> Modify SAP documentation

en/micro-integrator/docs/setup/message_builders_formatters/message-relay.md
- Fix message builder configurations for message relay
- Remove message relay module
- Fix broken links
Fix https://github.com/wso2/docs-ei/issues/864
=> Fix message relay section issues in docs

en/micro-integrator/docs/develop/k8s-samples/jms-sender-receiver.md
> Add jms sample for k8s samples
=> Add jms sample for k8s samples

en/ballerina-integrator/theme/material/main.html, en/home-page/theme/material/main.html, en/micro-integrator/theme/material/main.html, en/streaming-integrator/theme/material/main.html
=> Add Google Analytics for ei-docs

en/micro-integrator/docs/administer-and-observe/working-with-management-api.md
> Add docs related to management api
=> Add docs related to management api

en/micro-integrator/docs/setup/user_stores/setting_up_jdbc_userstore.md
Add JDBC user store parameter details and update doc
=> Update JDBC userstore config

en/micro-integrator/docs/setup/user_stores/setting_up_ro_ldap.md
=> Update read only LDAP userstore

en/micro-integrator/docs/administer-and-observe/working-with-management-api.md
> Add docs related to management api
=> Add management api docs

en/micro-integrator/docs/develop/creating-unit-test-suite.md
> Update the unit test creation document
=> Update the unit test creation document

en/micro-integrator/docs/setup/deployment/deploying_wso2_ei.md
=> Modify Deploy on VM docs

en/micro-integrator/docs/setup/brokers/configure-with-ActiveMQ.md
=> Correct the lib directory path

en/ballerina-integrator/theme/material/main.html, en/home-page/theme/material/main.html, en/micro-integrator/theme/material/main.html, en/streaming-integrator/theme/material/main.html
=> Move hotjar code from script to analytics block

en/micro-integrator/docs/setup/deployment/deployment_checklist.md, en/micro-integrator/docs/setup/transport_configurations/configuring-transports.md
> Fix documentation page Product Deployment Checklist
=> Fix documentation page Product Deployment Checklist

en/micro-integrator/docs/develop/creating-artifacts/encrypting-synapse-passwords.md
=> Fix doc issues in encrypting values in synapse

en/micro-integrator/docs/use-cases/examples/protocol-switching/switching_from_TCP_to_HTTPS.md, en/micro-integrator/docs/use-cases/examples/protocol-switching/switching_from_UDP_to_HTTPS.md
=> Fix UDP to HTTP

en/micro-integrator/docs/setup/brokers/configure-with-WSO2-MB.md
=> Fix toml issues in WSO2 MB

en/micro-integrator/docs/use-cases/examples/protocol-switching/switching_from_JMS_to_HTTP.md
=> Fix JMS to HTTP

en/micro-integrator/docs/setup/brokers/configure-with-WSO2-MB.md
> Add missing steps to comfigure with WSO2MB
=> Add missing steps

en/micro-integrator/docs/setup/deployment/file_based_registry.md
> Fix file_based_registry documentation page
=> Update file_based_registry doc

en/micro-integrator/docs/use-cases/examples/protocol-switching/switching_from_HTTPS_to_JMS.md, en/micro-integrator/docs/use-cases/examples/protocol-switching/switching_from_JMS_to_HTTP.md
=> Fix HTTP to JMS

en/micro-integrator/docs/setup/security/about_forgetme_tool.md, en/micro-integrator/docs/setup/security/gdpr_ei.md
> Fix 'Complying with GDPR' documentations
=> Update GDPR related docs

en/micro-integrator/docs/develop/advanced-development/generating-swagger-for-apis.md, en/micro-integrator/docs/setup/brokers/configure-with-WSO2-MB.md, en/micro-integrator/docs/setup/transport_configurations/configuring-transports.md, en/micro-integrator/docs/use-cases/examples/endpoint_examples/mtom-swa-with-endpoints.md
Fix transport configuration doc issues with toml parameters.
=> Fix transport configuration doc issues

en/micro-integrator/docs/references/troubleshooting-jms.md
Change JMS troubleshooting doc
=> Change JMS troubleshooting doc

en/micro-integrator/docs/administer-and-observe/jmx_monitoring.md, en/micro-integrator/docs/develop/advanced-development/applying-security-to-a-proxy-service.md, en/micro-integrator/docs/develop/creating-artifacts/creating-an-inbound-endpoint.md, en/micro-integrator/docs/references/mediators/callout-Mediator.md, en/micro-integrator/docs/references/mediators/payloadFactory-Mediator.md, en/micro-integrator/docs/references/synapse-properties/inbound-endpoints/event-based-inbound-endpoints/mqtt-inbound-endpoint-properties.md, en/micro-integrator/docs/references/synapse-properties/inbound-endpoints/event-based-inbound-endpoints/rabbitmq-inbound-endpoint-properties.md, en/micro-integrator/docs/references/synapse-properties/inbound-endpoints/listening-inbound-endpoints/cxf-ws-rm-inbound-endpoint-properties.md, en/micro-integrator/docs/references/synapse-properties/inbound-endpoints/listening-inbound-endpoints/hl7-inbound-endpoint-properties.md, en/micro-integrator/docs/references/synapse-properties/inbound-endpoints/listening-inbound-endpoints/http-inbound-endpoint-properties.md, en/micro-integrator/docs/references/synapse-properties/inbound-endpoints/listening-inbound-endpoints/websocket-inbound-endpoint-properties.md, en/micro-integrator/docs/setup/performance_tuning/jms_transport_tuning.md, en/micro-integrator/docs/setup/performance_tuning/tuning-the-VFS-Transport.md, en/micro-integrator/docs/use-cases/examples/jms_examples/consume-produce-jms.md, en/micro-integrator/docs/use-cases/examples/jms_examples/dual-channel-http-to-jms.md, en/micro-integrator/docs/use-cases/examples/jms_examples/producing-jms.md, en/micro-integrator/docs/use-cases/examples/jms_examples/publish-subscribe-with-jms.md, en/micro-integrator/docs/use-cases/examples/jms_examples/quad-channel-jms-to-jms.md, en/micro-integrator/docs/use-cases/examples/json_examples/json-examples.md, en/micro-integrator/docs/use-cases/examples/protocol-switching/switching_from_FIX_to_HTTP.md
Remove usage of templated files from the doc space.
=> Remove usage of templated files from the doc space.

en/micro-integrator/docs/develop/integration-development-kickstart.md
> Update response payload in Developing Your First Integration Solution documentation
=> Update healthcare service response

en/micro-integrator/docs/use-cases/examples/proxy_service_examples/Introduction-to-Proxy-Services.md, en/micro-integrator/docs/use-cases/examples/proxy_service_examples/exposing-proxy-via-inbound.md, en/micro-integrator/docs/use-cases/examples/proxy_service_examples/publishing-a-custom-wsdl.md, en/micro-integrator/docs/use-cases/examples/proxy_service_examples/securing-proxy-services.md
=> Modifying proxy services docs

en/micro-integrator/docs/use-cases/examples/transport_examples/Pub_Sub_using_MQTT.md, en/micro-integrator/docs/use-cases/examples/transport_examples/tcp-transport-examples.md
=> Modify Transport docs

en/micro-integrator/docs/setup/brokers/configure-with-Apache-Artemis.md, en/micro-integrator/docs/setup/brokers/configure-with-HornetQ.md, en/micro-integrator/docs/setup/brokers/configure-with-multiple-brokers.md, en/micro-integrator/docs/setup/brokers/configure-with-rabbitMQ.md
Fix issue in broker setup documentation
=> Fix broker doc issues

en/micro-integrator/docs/setup/transport_configurations/configuring-transports.md, en/micro-integrator/docs/use-cases/examples/protocol-switching/switching_from_HTTP_to_FIX.md, en/micro-integrator/docs/use-cases/examples/protocol-switching/switching_from_TCP_to_HTTPS.md
> Fix FIX transport config and HTTP to FIX document
=> Fix FIX transport config and HTTP to FIX

en/micro-integrator/docs/use-cases/examples/protocol-switching/switching_from_FIX_to_HTTP.md
Purpose
> Fix FIX to HTTP docs
=> Fix FIX to HTTP docs

en/micro-integrator/docs/use-cases/examples/jms_examples/consume-produce-jms.md, en/micro-integrator/docs/use-cases/examples/jms_examples/consuming-jms.md, en/micro-integrator/docs/use-cases/examples/jms_examples/detecting-repeatedly-redelivered-messages.md, en/micro-integrator/docs/use-cases/examples/jms_examples/dual-channel-http-to-jms.md, en/micro-integrator/docs/use-cases/examples/jms_examples/guaranteed-delivery-with-failover.md, en/micro-integrator/docs/use-cases/examples/jms_examples/producing-jms.md, en/micro-integrator/docs/use-cases/examples/jms_examples/publish-subscribe-with-jms.md, en/micro-integrator/docs/use-cases/examples/jms_examples/quad-channel-jms-to-jms.md, en/micro-integrator/docs/use-cases/examples/jms_examples/rabbitmq-examples.md, en/micro-integrator/docs/use-cases/examples/jms_examples/shared-topic-subscription.md, en/micro-integrator/docs/use-cases/examples/jms_examples/specifying-a-delivery-delay-on-messages.md
> Update Asynchronous Messaging documentation page.
@nilminiwso2 Need to add the relevant diagrams for [Detecting Repeatedly Redelivered Messages](https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/jms_examples/detecting-repeatedly-redelivered-messages/), [Specifying Delivery Delay on Messages](https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/jms_examples/specifying-a-delivery-delay-on-messages/), [SharedTopic Subscription](https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/jms_examples/shared-topic-subscription/) and [Rabbit MQ examples](https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/jms_examples/rabbitmq-examples/) sections.
=> Update Asynchronous Messaging documentation

en/micro-integrator/docs/use-cases/examples/protocol-switching/switching_from_FIX_to_AMQP.md
=> Fix FIX to AMQP docs

en/ballerina-integrator/docs/page-not-found.md, en/micro-integrator/docs/page-not-found.md, en/streaming-integrator/docs/page-not-found.md
'page not found' instructions.
=> page not found instructions

en/micro-integrator/docs/references/mediators/class-Mediator.md, en/micro-integrator/docs/references/mediators/dB-Report-Mediator.md, en/micro-integrator/docs/references/mediators/drop-Mediator.md, en/micro-integrator/docs/references/mediators/loopback-Mediator.md, en/micro-integrator/docs/references/mediators/payloadFactory-Mediator.md, en/micro-integrator/docs/references/mediators/respond-Mediator.md, en/micro-integrator/docs/references/mediators/send-Mediator.md, en/micro-integrator/docs/references/mediators/store-Mediator.md, en/micro-integrator/docs/setup/brokers/configure-with-ActiveMQ.md, en/micro-integrator/docs/setup/brokers/configure-with-WSO2-MB.md, en/micro-integrator/docs/setup/performance_tuning/tuning-the-VFS-Transport.md, en/micro-integrator/docs/use-cases/examples/file-processing/vfs-transport-examples.md, en/micro-integrator/docs/use-cases/examples/working-with-transactions.md
This is to remove definitions in synapse configs
=> Refactor example synapse configs

en/streaming-integrator/docs/guides/correlating-events.md, en/streaming-integrator/docs/guides/transforming-data.md
=> Fix two broken links and a header.

en/micro-integrator/docs/setup/installation/run_in_docker.md
Correct the file path in the 'create docker file manually' section.
=> Update create docker file manually section

en/micro-integrator/docs/references/synapse-properties/transport-parameters/jms-transport-parameters.md
Add toml parameters related to jms transport
=> Add toml parameters related to jms transport

en/streaming-integrator/docs/setup/deploying-si-as-minimum-ha-cluster.md, en/streaming-integrator/docs/setup/installing-si-in-vm.md
[1] and [2] are update with the system requirements in terms of the no of CPUs and the amount of memory.
[1] https://ei.docs.wso2.com/en/latest/streaming-integrator/setup/installing-si-in-vm/
[2] https://ei.docs.wso2.com/en/latest/streaming-integrator/setup/deploying-si-as-minimum-ha-cluster/
=> Mention the system requirements to run the SI in the Installation and the Minimum HA Cluster documentation.

en/micro-integrator/docs/develop/installing-WSO2-Integration-Studio.md
update tooling updates diagram.
=> update tooling image

en/streaming-integrator/docs/develop/debugging_siddhi_applications.md
=> Fix broken links in the Debugging Siddhi Applications page.

en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-kafka.md
=> 6th jan 7.0.0

en/micro-integrator/docs/use-cases/examples/routing_examples/routing_based_on_headers.md, en/micro-integrator/docs/use-cases/examples/routing_examples/routing_based_on_payloads.md, en/micro-integrator/docs/use-cases/examples/routing_examples/splitting_aggregating_messages.md, en/micro-integrator/mkdocs.yml
=> routing examples

en/home-page/docs/assets/js/theme.js, en/micro-integrator/docs/assets/js/theme.js, en/streaming-integrator/docs/assets/js/theme.js
=> Remove BI dropdown

en/micro-integrator/docs/references/comparisong-mi7-ei6xx.md
=> removing Ballerina

en/micro-integrator/docs/use-cases/examples/message_transformation_examples/json-to-soap-conversion.md, en/micro-integrator/docs/use-cases/examples/message_transformation_examples/pox-to-json-conversion.md
=> Message transform examples

en/micro-integrator/docs/references/config-catalog.md
Reflects the configuration change done to resolve https://github.com/wso2/micro-integrator/issues/1130
=> Change blocking builders/formatters

en/micro-integrator/docs/administer-and-observe/observability.md
Fixes https://github.com/wso2/micro-integrator/issues/1049 and reflect the changes in wso2/micro-integrator#1151
=> Update docs for correlation changes

en/micro-integrator/docs/administer-and-observe/observability.md
Fix the correlation log4j2 configs in docs
=> Update enabling co-relation logs docs.

en/home-page/docs/assets/css/theme.css, en/home-page/docs/index.md
In the EI docs home page, there is an alignment issue after the Ballerina integrator content has been removed. This PR fixes that issue and improves the UI styling.
=> Improve home page layout

en/micro-integrator/docs/setup/feature_configs/configuring-kafka.md, en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-kafka.md
=> Update docs with kafka configs

en/micro-integrator/docs/setup/deployment/k8s-samples/jms-sender-receiver.md, en/micro-integrator/docs/setup/installation/run_in_docker.md
Adds documentation changes required for https://github.com/wso2/micro-integrator/issues/1107
=> Change path for MI_HOME in docker

en/micro-integrator/docs/administer-and-observe/using-the-command-line-interface.md
=> Update MI CLI log-level command documentation

en/micro-integrator/mkdocs.yml
=> Revert "Update mkdocs.yml"

en/streaming-integrator/docs/admin/monitoring-the-streaming-integrator.md, en/streaming-integrator/docs/develop/working-with-the-Design-View.md, en/streaming-integrator/docs/setup/configuring-data-sources.md, en/streaming-integrator/docs/setup/deploying-si-as-a-scalable-cluster.md, en/streaming-integrator/docs/setup/installing-si-in-vm.md
=> Correct broken links in Streaming Integrator documentation.

en/streaming-integrator/mkdocs.yml
=> Fix broken link in the navigator.

en/micro-integrator/docs/use-cases/tutorials/using-inbound-endpoints.md
=> Fix issue with Inbound Endpoint supportive jar

en/micro-integrator/docs/use-cases/tutorials/using-templates.md
=> Fix try-it curl port number in using-template sample

en/micro-integrator/docs/develop/create-docker-project.md
images are misplaced when the window is small.
=> image misplaced

en/micro-integrator/docs/administer-and-observe/using-the-command-line-interface.md
=> Fix issues 7.0.0

en/micro-integrator/mkdocs.yml
> This PR contains the updated mkdocs.yml for Amazon Lambda.
=> Update mkdocs.yml for Amazon Lambda

en/micro-integrator/docs/use-cases/tutorials/storing-and-forwarding-messages.md
Deployment.toml configurations provided in https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/tutorials/storing-and-forwarding-messages/ is incorrect. Hence corrected them.
Addresses: #1048
=> Correct configurations for broker integration

en/micro-integrator/docs/use-cases/tutorials/storing-and-forwarding-messages.md
Deployment.toml configurations provided in https://ei.docs.wso2.com/en/next/micro-integrator/use-cases/tutorials/storing-and-forwarding-messages/ is incorrect. Hence corrected them. 
Addresses: https://github.com/wso2/docs-ei/issues/1048
=> Correct configurations for broker

en/micro-integrator/docs/develop/hot-deployment.md, en/micro-integrator/docs/references/config-catalog.md, en/micro-integrator/mkdocs.yml
Updated the yaml and few other edits.
=> hot deployment yaml

en/micro-integrator/docs/use-cases/tutorials/using-the-gmail-connector.md
Fixes https://github.com/wso2/docs-ei/issues/1084
=> gmail connector tutorial

en/micro-integrator/docs/use-cases/tutorials/exposing-several-services-as-a-single-service.md, en/micro-integrator/docs/use-cases/tutorials/file-processing.md, en/micro-integrator/docs/use-cases/tutorials/routing-requests-based-on-message-content.md, en/micro-integrator/docs/use-cases/tutorials/sending-a-simple-message-to-a-datasource.md, en/micro-integrator/docs/use-cases/tutorials/sending-a-simple-message-to-a-service.md, en/micro-integrator/docs/use-cases/tutorials/storing-and-forwarding-messages.md, en/micro-integrator/docs/use-cases/tutorials/transforming-message-content.md, en/micro-integrator/docs/use-cases/tutorials/using-inbound-endpoints.md, en/micro-integrator/docs/use-cases/tutorials/using-scheduled-tasks.md, en/micro-integrator/docs/use-cases/tutorials/using-templates.md, en/micro-integrator/docs/use-cases/tutorials/using-the-gmail-connector.md
=> tutorial CLI instructions + improvements

en/micro-integrator/docs/setup/performance_tuning/http_transport_tuning.md, en/micro-integrator/docs/use-cases/tutorials/exposing-several-services-as-a-single-service.md, en/micro-integrator/docs/use-cases/tutorials/file-processing.md, en/micro-integrator/docs/use-cases/tutorials/routing-requests-based-on-message-content.md, en/micro-integrator/docs/use-cases/tutorials/sending-a-simple-message-to-a-datasource.md, en/micro-integrator/docs/use-cases/tutorials/sending-a-simple-message-to-a-service.md, en/micro-integrator/docs/use-cases/tutorials/storing-and-forwarding-messages.md, en/micro-integrator/docs/use-cases/tutorials/transforming-message-content.md, en/micro-integrator/docs/use-cases/tutorials/using-inbound-endpoints.md, en/micro-integrator/docs/use-cases/tutorials/using-scheduled-tasks.md, en/micro-integrator/docs/use-cases/tutorials/using-templates.md, en/micro-integrator/docs/use-cases/tutorials/using-the-gmail-connector.md
Fixes https://github.com/wso2/docs-ei/issues/1085
=> tutorials CLI instructions +  improvements

en/micro-integrator/docs/use-cases/examples/template_examples/using-endpoint-templates.md
remove WIP banner as [1] is fixed.
[1] wso2/devstudio-tooling-ei#516
=> removed WIP note

en/micro-integrator/docs/use-cases/examples/template_examples/using-endpoint-templates.md
remove WIP banner as [1] is fixed.
[1] https://github.com/wso2/devstudio-tooling-ei/issues/516
=> remove WIP banner

en/micro-integrator/docs/use-cases/tutorials/file-processing.md
1. Removed an unused jar groovy-all-1.1-rc-1.jar
2. Changed an expression in the databaseSequence configuration.
3. Mention that users may need to allow less secure apps option in google account in order to send emails.
=> Improve tutorial: File Processing

en/micro-integrator/docs/setup/transport_configurations/configuring-transports.md
=> Typo fix on the filename when configuring FIX transport

en/micro-integrator/mkdocs.yml
> This PR contains updated mkdocs.yml for Dynamics365 connector.
=> Update mkdocs.yml for Dynamics365

en/micro-integrator/docs/references/connectors/ISO8583-connector/ISO8583-connector-configuration.md
> This PR contains the "ISO8583-connector-configuration.md".
=> Add ISO8583-connector-configuration.md

en/micro-integrator/docs/use-cases/examples/data_integration/odata-service.md
Fix syntax errors in Odata sample
=> Fix Dataservice OData sample docs

en/micro-integrator/docs/use-cases/examples/data_integration/odata-service.md
Fix OData sample syntax errors
=> Fix Dataservice OData sample

en/micro-integrator/docs/develop/WSO2-Integration-Studio.md
Edit quick tour guide perspective switch details
=> Edit quick tour guide

en/micro-integrator/docs/use-cases/tutorials/using-templates.md
Added details on how to use newly added HTTP4 client to send requests.
Tutorial: https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/tutorials/using-templates/
Related Issues: https://github.com/wso2/devstudio-tooling-ei/issues/833
=> Update Using Template Tutorial

en/micro-integrator/docs/use-cases/examples/data_integration/nested-queries-in-data-service.md
Add nested queries sample changes
=> Add changes to nested queries sample

en/micro-integrator/docs/references/mediators/script-Mediator.md, en/micro-integrator/docs/use-cases/examples/json_examples/json-examples.md
=> JDK compatibility for JSON with Nashorn Engine used in Script Mediator

en/micro-integrator/docs/use-cases/examples/protocol-switching/switching_from_TCP_to_HTTPS.md
1.  Improve the format of the synapse configuration
2.  Add outcomes so that users can verify the behavior
Doc link: https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/protocol-switching/switching_from_TCP_to_HTTPS/
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/848
=> Improve TCP to HTTP example

en/micro-integrator/docs/use-cases/examples/data_integration/batch-requesting.md
Refactor DS Batch requesting sample
=> Refactor DS Batch requesting sample

en/micro-integrator/docs/use-cases/examples/protocol-switching/switching_from_UDP_to_HTTPS.md
1. Fixing synapse configuration
2. Correcting the request
Doc: https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/protocol-switching/switching_from_UDP_to_HTTPS/
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/848
=> Fixing UPD-HTTP example

en/micro-integrator/docs/references/connectors/kafka-connector/setting-up-kafka.md
>This PR includes updated setting-up-kafka.md. (Remove inboundendpoint configuration)
=> Remove inboundendpoint configuration

en/micro-integrator/docs/references/connectors/ISO8583-connector/ISO8583-connector-configuration.md
> This PR contains added inbound endpoint configuration to the ISO8583-connector config.md.
=> Add inbound endpoint configuration

en/micro-integrator/docs/references/connectors/salesforce-connector/sf-connector-configuration.md
Add latest doc URLs for reference
=> Add latest documentation URLs

en/micro-integrator/docs/use-cases/examples/jms_examples/rabbitmq-examples.md
=> Fix issue in the AMQPProxy configuration

en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/file-inbound-endpoint.md
Refactor file inbound endpoint docs
=> Refactor file inbound endpoint docs

en/micro-integrator/docs/use-cases/examples/proxy_service_examples/securing-proxy-services.md
Refactor secure proxy service docs
=> Refactor secure proxy service docs

en/micro-integrator/docs/use-cases/examples/proxy_service_examples/publishing-a-custom-wsdl.md
=> Refactor custom wsdl doc

en/micro-integrator/mkdocs.yml
> This PR contains updated mkdocs file.
=> Update mkdocs content.

en/micro-integrator/mkdocs.yml
=> mkdocs.yaml fix

en/micro-integrator/docs/overview/key-concepts.md
Updating the 'Data Service' section.
=> updated data services

en/micro-integrator/docs/overview/key-concepts.md
Updated data services section.
=> updated data services.

en/streaming-integrator/docs/ref/store-APIs.md
=> Correct sample CURL command in Store API documentation.

en/streaming-integrator/docs/ref/store-APIs.md
=> Change port in curl command from 9443 to 7443.

en/micro-integrator/mkdocs.yml
>This PR includes updated mkdocs for azure storage connector.
=> Update mkdocs for azure

en/micro-integrator/docs/develop/creating-artifacts/data-services/securing-data-services.md, en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-https-protocol.md
Refactor HTTPS Inbound endpoint docs and Securing Dataservices docs
=> Refactor HTTPS Inbound endpoint docs and Securing Dataservices docs

en/micro-integrator/docs/develop/creating-artifacts/data-services/securing-data-services.md, en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-https-protocol.md
Refactor HTTPS Inbound endpoint docs and Securing Dataservices docs
=> Refactor HTTPS IE and Secure DSS docs

en/micro-integrator/docs/setup/brokers/configure-with-ActiveMQ.md, en/micro-integrator/docs/setup/installation/run_in_docker.md
=> Revert "Update ActiveMQ configuration doc"

en/micro-integrator/mkdocs.yml
> This PR include updated mkdocs for FHIR connector.
=> Update mkdocs for FHIR connector

en/micro-integrator/docs/references/connectors/ISO8583-connector/ISO8583-connector-example.md, en/micro-integrator/docs/references/connectors/ISO8583-connector/ISO8583-inbound-endpoint-example.md, en/micro-integrator/docs/references/connectors/amazonlambda-connector/amazonlambda-connector-example.md, en/micro-integrator/docs/references/connectors/amazonlambda-connector/setting-up-amazonlambda.md, en/micro-integrator/docs/references/connectors/amazons3-connector/amazons3-connector-config.md, en/micro-integrator/docs/references/connectors/amazons3-connector/amazons3-connector-example.md, en/micro-integrator/docs/references/connectors/amazonsqs-connector/amazonsqs-connector-example.md, en/micro-integrator/docs/references/connectors/db-event-inbound-endpoint/db-event-inbound-endpoint-example.md, en/micro-integrator/docs/references/connectors/exporting-artifacts.md, en/micro-integrator/docs/references/connectors/fhir-connector/fhir-connector-example.md, en/micro-integrator/docs/references/connectors/file-connector/file-connector-example.md, en/micro-integrator/docs/references/connectors/gmail-connector/configuring-gmail-api.md, en/micro-integrator/docs/references/connectors/gmail-connector/gmail-connector-example.md, en/micro-integrator/docs/references/connectors/google-firebase-connector/google-firebase-connector-example.md, en/micro-integrator/docs/references/connectors/google-firebase-connector/google-firebase-setup.md, en/micro-integrator/docs/references/connectors/importing-connector-to-integration-studio.md, en/micro-integrator/docs/references/connectors/kafka-connector/kafka-connector-producer-example.md, en/micro-integrator/docs/references/connectors/kafka-connector/kafka-inbound-endpoint-example.md, en/micro-integrator/docs/references/connectors/microsoft-azure-storage-connector/microsoft-azure-storage-configuration.md, en/micro-integrator/docs/references/connectors/microsoft-azure-storage-connector/microsoft-azure-storage-connector-example.md, en/micro-integrator/docs/references/connectors/microsoft-dynamics365-connector/microsoft-dynamics365-configuration.md, en/micro-integrator/docs/references/connectors/salesforce-rest-connector/sf-access-token-generation.md, en/micro-integrator/docs/references/connectors/salesforce-rest-connector/sf-rest-connector-example.md, en/micro-integrator/docs/references/connectors/servicenow-connector/servicenow-connector-example.md, en/micro-integrator/docs/references/connectors/servicenow-connector/settingup-servicenow-instance.md, en/micro-integrator/mkdocs.yml
This fixes a set of broken images for connector docs.
=> Fixing broken images

en/micro-integrator/docs/use-cases/examples/json_examples/json-examples.md
1. Add a missing quote (") in a request.
2. Correct registry resource file name.
Related PR: https://github.com/wso2/docs-ei/pull/1393
=> Fix Json examples Tutorial

en/micro-integrator/docs/use-cases/examples/transport_examples/tcp-transport-examples.md
Changing all tcp ports to 6060
=> Fix example tranports tcp

en/micro-integrator/docs/use-cases/examples/sequence_examples/using-multiple-sequences.md
Change the xpath according to the request given.
=> Fix example multiple sequence

en/micro-integrator/docs/use-cases/examples/sequence_examples/using-multiple-sequences.md
Change the XPath according to the request given.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/877
=> Fix example breaking flows to multiple sequence

en/micro-integrator/docs/use-cases/examples/protocol-switching/switching_from_FTP_listener_to_mail_sender.md
Correcting the synapse configuration.
=> Correcting ftp-mail example

en/micro-integrator/docs/use-cases/examples/file-processing/vfs-transport-examples.md
Correcting the synapse configuration
1.  Adding a header
2.  Restructuring the configuration
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/860
=> Improving the VFS Transport Tutorial

en/micro-integrator/docs/use-cases/examples/file-processing/Accessing_Windows_Share_Using_VFS_Transport.md
1.  Add some missing details on the setting up.
2.  Correcting the synapse configuration.
https://github.com/wso2/devstudio-tooling-ei/issues/860
=> Improve example Windows Share

en/micro-integrator/docs/use-cases/examples/file-processing/mailto-transport-examples.md
Add missing steps
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/860
=> Improve mailto example

en/micro-integrator/docs/use-cases/examples/rest_api_examples/setting-query-params-outgoing-messages.md
=> Correcting query parameter restApI example

en/micro-integrator/docs/use-cases/examples/template_examples/using-endpoint-templates.md
Adding namespace
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/868
=> Fix example using endpoint template

en/micro-integrator/docs/use-cases/examples/registry_examples/local-registry-entries.md
1. Removed `definitions` related details as it is not used.
2. Updated some of the content following the doc from [EI-6.6.0](https://docs.wso2.com/display/EI660/Sample+14%3A+Using+Sequences+and+Endpoints+as+Local+Registry+Items)
=> Update example- sequence as local entry

en/micro-integrator/docs/use-cases/examples/file-processing/mailto-transport-examples.md
=> Improve maito example

en/micro-integrator/docs/use-cases/examples/rest_api_examples/introduction-rest-api.md
=> Improve RestAPI example

en/micro-integrator/docs/use-cases/examples/endpoint_examples/using-wsdl-endpoints.md
Add a new entry to wsdl file as the existing one are cannot be found when running. Changing the synapse configurations and others accordingly.
Related PR (WSDL new port): https://github.com/wso2-docs/WSO2_EI/pull/68
=> Fix example wsdl endpoint

en/micro-integrator/docs/use-cases/examples/sequence_examples/using-fault-sequences.md
Change the request message according to the XPATH evaluation.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/877
=> Fix example fault sequence

en/micro-integrator/docs/use-cases/examples/proxy_service_examples/Introduction-to-Proxy-Services.md
Refactor introduction to proxy services
=> Refactor introduction to proxy services

en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-http-protocol.md
=> Fix HTTP Inbound endpoint doc

en/micro-integrator/docs/setup/security/encrypting_plain_text.md
=> Update execution command.

en/micro-integrator/docs/setup/security/securing_management_api.md
Fixes https://github.com/wso2/micro-integrator/issues/1399
=> Update securing mangement api with templated changes

en/micro-integrator/docs/references/connectors/salesforce-rest-connector/sf-rest-connector-config.md
> Add sample values to Salesforce Rest connector documentation.
=> Update SF connector sample values

en/streaming-integrator/docs/guides/consuming-messages.md, en/streaming-integrator/docs/quick-start-guide/getting-started/create-the-siddhi-application.md, en/streaming-integrator/mkdocs.yml
=> Correct broken links in the navigator.

en/micro-integrator/docs/references/connectors/ldap-connector/ldap-connector-example.md, en/micro-integrator/docs/references/connectors/ldap-connector/ldap-server-configuration.md, en/micro-integrator/docs/references/connectors/ldap-connector/setting-up-ldap.md, en/micro-integrator/mkdocs.yml
Add LDAP reference documentation + few links.
=> LDAP reference

en/micro-integrator/docs/references/connectors/salesforce-rest-connector/sf-rest-connector-example.md
Adds minor fixes to include missing changes.
=> Minor fixes

en/micro-integrator/mkdocs.yml
> Add sales force inbound endpoint files path to the mkdocs.
=> Add sf-inboundEP path

en/micro-integrator/docs/references/synapse-properties/data-services.md
> Add dataservice swagger feature docs.
Related to wso2/micro-integrator/issues/1331
=> Add dataservice swagger feature docs.

en/micro-integrator/docs/use-cases/tutorials/using-scheduled-tasks.md
fixes https://github.com/wso2/docs-ei/issues/1231
=> injectTo=sequence

en/micro-integrator/mkdocs.yml
> This PR contains Sales force inbound endpoint reference doc yml path.
=> Add reference doc yml path

en/micro-integrator/docs/use-cases/examples/integrating-mi-with-si.md
=> Add doc on how to integrate MI with SI.

en/micro-integrator/docs/references/connectors/ISO8583-connector/ISO8583-connector-example.md
> This PR includes fixed minor changes in ISO8583 connector.
=> Fix minor changes

en/micro-integrator/docs/references/connectors/salesforce-rest-connector/sf-rest-inbound-endpoint-reference-configuration.md
> This PR contains sf-rest inbound endpoint reference configuration document.
=> Add sf-rest-inbound-endpoint-reference-configuration

en/micro-integrator/docs/references/connectors/fhir-connector/fhir-connector-config.md
Adds reference content for the FHIR connector.
=> FHIR reference docs

en/micro-integrator/docs/setup/transport_configurations/configuring-transports.md
=> Fix broken link

en/micro-integrator/docs/setup/installation/run_in_docker.md
Fixes https://github.com/wso2/docs-ei/issues/1493.
=> mi image name fixed

en/micro-integrator/docs/develop/creating-artifacts/encrypting-synapse-passwords.md
> Related fix: https://github.com/wso2/micro-integrator/pull/1422
=> Remove warning to create securevault.properties file

en/micro-integrator/docs/setup/message_builders_formatters/message-builders-and-formatters.md
In Custom message formatter section, [[custom_message_builders]] shoul be corrected.
> Link to the PR for changes to the training …
=> Update custom message formatter section

en/micro-integrator/docs/develop/customizations/creating-synapse-handlers.md, en/micro-integrator/docs/references/config-catalog.md
Add docs related to configuring synapse handlers in deployment.toml file.
=> Configure synapse-handlers in deployment.toml file

en/micro-integrator/docs/setup/brokers/configure-with-rabbitMQ.md
=> Update configure with rabbit mq doc.

en/streaming-integrator/docs/connectors/downloading-and-Installing-Siddhi-Extensions.md
=> Revert changes made in the 7.0.0 branch for the Extension Installer

en/streaming-integrator/docs/setup/deploying-si-as-minimum-ha-cluster-in-aws-ecs.md
=> Remove an obsolete Work In Progress banner.

en/micro-integrator/docs/references/connectors/salesforce-rest-connector/sf-rest-overview.md
> This PR include sf-rest connector overview page.
=> Add sf-rest connector overview

en/micro-integrator/docs/references/connectors/amazonlambda-connector/amazonlambda-connector-example.md
> This PR includes updated document for Amazon lambda connector example.
=> Reorganize the document structure

en/micro-integrator/docs/references/connectors/salesforce-rest-connector/sf-rest-inbound-endpoint-configuration.md, en/micro-integrator/docs/references/connectors/salesforce-rest-connector/sf-rest-inbound-endpoint-example.md
> This PR includes update formatting changes in Salesforce Inbound Endpoint.
=> Update formatting changes

en/micro-integrator/docs/administer-and-observe/using-the-command-line-interface.md
> Add docs for encryption client CLI commands.
=> Add encryption client CLI commands

en/streaming-integrator/docs/admin/creating-business-rules-templates.md, en/streaming-integrator/docs/develop/streaming-integrator-studio-overview.md, en/streaming-integrator/docs/examples/streaming-data-from-oracle-to-kafka.md, en/streaming-integrator/docs/ref/environment-compatibility.md, en/streaming-integrator/docs/setup/change-hostname-and-context-path.md, en/streaming-integrator/mkdocs.yml
=> Add instructions to change the host name and the name of web UI applications

en/streaming-integrator/mkdocs.yml
=> Fix broken link.

en/micro-integrator/mkdocs.yml
> This PR includes SMPP connector mkdocs yaml.
=> Update mkdocs for SMPP

en/micro-integrator/docs/administer-and-observe/working-with-management-api.md
> Add artifact suspension api commands for proxy and endpoints.
> Fixes: https://github.com/wso2/micro-integrator/issues/1524
=> Update management api docs.

en/micro-integrator/docs/references/connectors/smpp-connector/smpp-inbound-endpoint-example.md
> This PR includes smpp-inbound-endpoint-example documentation.
=> Add smpp-inbound-endpoint-example

en/micro-integrator/docs/references/connectors/smpp-connector/smpp-connector-config.md
> This PR includes smpp-connector-config.md documentation.
=> Add smpp-connector-config.md

en/streaming-integrator/docs/setup/configuring-business-rules-deployment.md, en/streaming-integrator/mkdocs.yml
#1407  Security checks
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines?Yes
=> Add the Configuring Business Rules Deployment section.

en/micro-integrator/docs/setup/security/securing_management_api.md
Updates the documentation with the newly added Authorization handler and the changed toml configurations for the management api.
=> Update securing management api

en/micro-integrator/docs/references/connectors/amazons3-connector/amazons3-connector-reference.md, en/micro-integrator/mkdocs.yml
=> Add Amazon S3

en/micro-integrator/docs/references/connectors/amazons3-connector/amazons3-connector-reference.md, en/micro-integrator/docs/references/connectors/microsoft-azure-storage-connector/microsoft-azure-storage-reference.md, en/micro-integrator/mkdocs.yml
Reference documentation for Microsoft Azure Storage Connector.
=> Azure Storage Connector

en/micro-integrator/docs/references/connectors/ISO8583-connector/ISO8583-connector-reference.md, en/micro-integrator/docs/references/connectors/amazonsqs-connector/amazonsqs-connector-config.md, en/micro-integrator/docs/references/connectors/salesforce-rest-connector/sf-rest-connector-config.md, en/micro-integrator/mkdocs.yml
ISO8583 Connector Reference Docs
=> ISO8583 Connector Reference Docs

en/streaming-integrator/docs/ref/authentication-APIs.md, en/streaming-integrator/docs/ref/business-Rules-APIs.md, en/streaming-integrator/docs/ref/event-simulation-apis.md, en/streaming-integrator/docs/ref/hTTP-Status-Codes.md, en/streaming-integrator/docs/ref/healthcheck-APIs.md, en/streaming-integrator/docs/ref/permission-apis.md, en/streaming-integrator/docs/ref/public-APIs.md, en/streaming-integrator/docs/ref/si-rest-api-guide.md, en/streaming-integrator/docs/ref/siddhi-Application-Management-APIs.md, en/streaming-integrator/docs/ref/status-monitoring-apis.md, en/streaming-integrator/docs/ref/store-APIs.md, en/streaming-integrator/docs/ref/stream-Processor-REST-API-Guide.md, en/streaming-integrator/docs/setup/configuring-business-rules-deployment.md, en/streaming-integrator/mkdocs.yml
=> Make formatting correction

en/micro-integrator/docs/use-cases/examples/jms_examples/consuming-jms.md
> This PR contains adding a mandatory parameter to the given proxy in the Example1.
=> add mandatory parameter to the proxy in example1

en/micro-integrator/docs/use-cases/tutorials/transforming-message-content.md
Correct the backend service payload in the Message Transformation sample.
=> Correct json payload in Message Transformation sample

en/micro-integrator/docs/references/connectors/kafka-connector/kafka-inbound-endpoint-example.md
Correcting Kafka sample configuration parameters.
=> Correct Kafka sample configuration

en/micro-integrator/docs/references/connectors/amazonsqs-connector/amazonsqs-connector-config.md, en/micro-integrator/mkdocs.yml
Adding FHIR Reference documentation.
=> FHIR Config

en/micro-integrator/mkdocs.yml
> This PR includes updated mkdocs for DynamoDB example.
=> Update mkdocs for DynamoDB

en/micro-integrator/docs/references/connectors/ISO8583-connector/ISO8583-inbound-endpoint-config.md, en/micro-integrator/mkdocs.yml
=> ISO8583 Inbound Endpoint docs

en/streaming-integrator/docs/ref/rest-api-guide-overview.md, en/streaming-integrator/docs/ref/siddhi-Application-Management-APIs.md, en/streaming-integrator/mkdocs.yml
=> Complete the Streaming Integrator REST API Guide.

en/streaming-integrator/mkdocs.yml
=> Fix broken links in the navigator.

en/micro-integrator/docs/administer-and-observe/monitoring_with_prometheus.md
=> Update Prometheus readme.

en/micro-integrator/docs/setup/security/encrypting_plain_text.md
Fix https://github.com/wso2/micro-integrator/issues/1596
=> Fix https://github.com/wso2/micro-integrator/issues/1596

en/micro-integrator/docs/setup/security/encrypting_plain_text.md
Fixes:  https://github.com/wso2/docs-ei/issues/1597
=> Fix https://github.com/wso2/docs-ei/issues/1597

en/micro-integrator/docs/references/connectors/smpp-connector/smpp-inbound-endpoint-config.md
> This PR includes SMPP inbound endpoint reference document.
=> Add SMPP inbound endpoint reference doc

en/streaming-integrator/docs/ref/event-simulation-apis.md, en/streaming-integrator/mkdocs.yml
=> Correct links in the SI documentation navigator

en/micro-integrator/docs/references/connectors/google-spreadsheet-connector/google-spreadsheet-connector-config.md, en/micro-integrator/docs/references/connectors/google-spreadsheet-connector/google-spreadsheet-connector-example.md, en/micro-integrator/mkdocs.yml
=> Google spreadsheet

en/micro-integrator/docs/references/connectors/amazonsqs-connector/amazonsqs-inbound-endpoint-reference-configuration.md
> This PR includes reference doc for AmazonSQS inbound endpoint document.
=> Add refernce doc for AmazonSQS inbound endpoint

en/micro-integrator/docs/references/connectors/file-connector/file-connector-config.md
With file connector version 2.0.22, the parameter ``source`` is changed to ``filePath`` in file create operation.
=> Update file connector create operation

en/streaming-integrator/docs/ref/authentication-APIs.md, en/streaming-integrator/docs/ref/business-Rules-APIs.md, en/streaming-integrator/docs/ref/event-simulation-apis.md, en/streaming-integrator/docs/ref/hTTP-Status-Codes.md, en/streaming-integrator/docs/ref/healthcheck-APIs.md, en/streaming-integrator/docs/ref/permission-apis.md, en/streaming-integrator/docs/ref/rest-api-guide-overview.md, en/streaming-integrator/docs/ref/siddhi-Application-Management-APIs.md, en/streaming-integrator/docs/ref/store-APIs.md, en/streaming-integrator/docs/setup/configuring-business-rules-deployment.md, en/streaming-integrator/docs/setup/configuring-data-sources.md, en/streaming-integrator/mkdocs.yml
=> Correct broken links in HTML tables.

en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-https-protocol.md
Fixes https://github.com/wso2/docs-ei/issues/1435
=> added note

en/micro-integrator/docs/develop/hot-deployment.md
To reflect changes in https://github.com/wso2/micro-integrator/pull/1606
=> Update hot deployment docs

en/micro-integrator/docs/references/mediators/property-Mediator.md
Fixes https://github.com/wso2/docs-ei/issues/1408
=> property mediator - dynamic name

en/micro-integrator/docs/references/connectors/amazonsqs-connector/amazonsqs-inbound-endpoint-example.md
> This PR includes Amazon SQS Inbound Endpoint example documentation.
=> Amazonsqs inbound endpoint example

en/streaming-integrator/docs/quick-start-guide/getting-started/create-the-siddhi-application.md, en/streaming-integrator/docs/ref/business-Rules-APIs.md, en/streaming-integrator/docs/ref/event-simulation-apis.md, en/streaming-integrator/docs/ref/healthcheck-APIs.md, en/streaming-integrator/docs/ref/permission-apis.md, en/streaming-integrator/docs/ref/siddhi-Application-Management-APIs.md, en/streaming-integrator/docs/ref/store-APIs.md, en/streaming-integrator/mkdocs.yml
=> Add missing information and improve the SI REST API Guide

en/micro-integrator/docs/administer-and-observe/working-with-management-api.md
Update 'Using the Management API' documentation to reflect the improvement done in [1].
[1] https://github.com/wso2/micro-integrator/pull/1158
=> Update using the Management API doc with logging resource details

en/micro-integrator/docs/develop/creating-artifacts/encrypting-synapse-passwords.md
=> Refactor syntax in sample

en/micro-integrator/mkdocs.yml
=> Revert "testing the doc build"

en/micro-integrator/docs/develop/inject_env_variables_to_embedded_mi.md
sending erroneous correction to to test the build script.
=> testing the build 2

en/micro-integrator/docs/develop/inject_env_variables_to_embedded_mi.md
=> Revert "testing the build 2"

en/micro-integrator/mkdocs.yml
=> Revert "Revert "testing the doc build""

en/micro-integrator/mkdocs.yml
=> Revert "Revert "Revert "testing the doc build"""

en/micro-integrator/mkdocs.yml
=> Revert "Revert "Revert "Revert "testing the doc build""""

en/micro-integrator/docs/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-kafka.md
Fixes: https://github.com/wso2/docs-ei/issues/1674
=> Fix: https://github.com/wso2/docs-ei/issues/1674

en/micro-integrator/mkdocs.yml
=> Revert "Revert "Revert "Revert "Revert "testing the doc build"""""

en/micro-integrator/docs/use-cases/examples/file-processing/Accessing_Windows_Share_Using_VFS_Transport.md
> Fixes: https://github.com/wso2/micro-integrator/issues/1618
=> Update SMB sample to add provider jar

en/micro-integrator/docs/setup/security/encrypting_plain_text.md
> Modify docs on using dynamic secrets.
=> Modify using dynamic secret section

en/micro-integrator/mkdocs.yml
This is an erroneous PR.
Testing the build script for EI docs.
=> erroneous mkdocs.yml

en/micro-integrator/mkdocs.yml
=> Revert "erroneous mkdocs.yml"

en/micro-integrator/docs/setup/security/gdpr_ei.md
=> Refactor GDPR doc for MI.

en/micro-integrator/docs/administer-and-observe/using-the-command-line-interface.md, en/micro-integrator/docs/administer-and-observe/working-with-management-api.md, en/micro-integrator/docs/setup/enabling_transaction_counter.md
Add docs for the transaction counter component.
=> Add transaction counter component docs

en/micro-integrator/docs/administer-and-observe/using-the-command-line-interface.md, en/micro-integrator/docs/administer-and-observe/working-with-management-api.md, en/micro-integrator/docs/setup/enabling_transaction_counter.md, en/micro-integrator/mkdocs.yml
transaction counter docs - minor fixes
=> transaction counter doc minor fixes

en/micro-integrator/docs/references/connectors/salesforcebulk-connector/salesforcebulk-connector-configuration.md
> This PR includes salesforcebulk-connector-configuration documentation.
=> Add salesforcebulk-connector-configuration doc

en/micro-integrator/docs/references/connectors/kafka-connector/kafka-connector-config.md
> Fix documentation issue with connectionsMaxIdleTime parameter
=> Fix documentation issue

en/micro-integrator/docs/administer-and-observe/working-with-management-api.md
> This pr contains the update of the logout command since the exiting one was not working.
=> Update the logout command.

en/micro-integrator/docs/setup/brokers/configure-with-ActiveMQ.md
Minor fixes as a result of terminology changes.
=> Terminology3

en/micro-integrator/docs/references/connectors/fhir-connector/fhir-connector-config.md
Adds missing FHIR reference content.
=> Fhir reference

en/micro-integrator/docs/references/connectors/amazons3-connector/amazons3-connector-reference.md
> Add missing operations to Amazon S3 Connector documentation
=> Add missing operations to Amazon S3 Connector documentation

en/micro-integrator/docs/references/connectors/amazonlambda-connector/amazonlambda-connector-config.md
> This PR include updated reference doc for Amazon Lambda Connector.
=> Update reference doc

en/micro-integrator/docs/references/connectors/google-spreadsheet-connector/google-spreadsheet-connector-config.md
> This documentation includes updated reference documentation for Google-Spreadsheet-Connector.
=> Update reference doc Google-Spreadsheet-Connector

en/micro-integrator/docs/references/mediators/property-Mediator.md, en/micro-integrator/docs/references/mediators/property-reference/accessing-properties-with-xpath.md
This PR updates the relevant documentation on environment scope support for property mediator.
Related PR https://github.com/wso2-support/wso2-synapse/pull/804
=> [7.0.0] Add environment scope to property mediator doc

en/micro-integrator/docs/references/mediators/property-Mediator.md, en/micro-integrator/docs/references/mediators/property-reference/accessing-properties-with-xpath.md
This PR updates the relevant documentation on environment scope support for property mediator.
Related PR https://github.com/wso2/wso2-synapse/pull/1451
=> Add environment scope to property mediator doc

en/micro-integrator/docs/use-cases/examples/sequence_examples/using-multiple-sequences.md
Add the namespace to make the seq correct
=> Correct the synapse config

en/micro-integrator/docs/references/connectors/email-connector/email-connector-config.md
> Add default values to email connector.
=> Update email connector docs

en/micro-integrator/docs/setup/security/encrypting_plain_text.md
Related PR https://github.com/wso2/product-mi-tooling/pull/63
=> Update docs removing encription folder dependency

en/micro-integrator/docs/administer-and-observe/working-with-monitoring-dashboard.md
update the dashboard url to 'http://localhost:9390/dashboard/login'
=> update the dashboard url

en/micro-integrator/docs/setup/brokers/configure-with-IBM-websphereMQ.md
Related issue https://github.com/wso2/product-ei/issues/5169
=> Add IBM MQ MQCSP authentication mode related details

en/micro-integrator/docs/references/connectors/fhir-connector/fhir-connector-example.md
> This PR includes messageFormatters and builders section in FHIR connector example.
=> Update FHIR formatters

en/micro-integrator/docs/references/connectors/fhir-connector/fhir-connector-example.md
=> Update FHIR sample

en/micro-integrator/docs/references/connectors/why-connectors.md
Fixed broken connector images.
=> Fixed images

en/micro-integrator/docs/references/connectors/salesforcebulk-connector/salesforcebulk-reference.md
> This PR includes salesforcebulk-reference.md.
=> Add salesforcebulk-reference.md

en/micro-integrator/docs/references/config-catalog.md, en/micro-integrator/docs/setup/user_stores/setting_up_a_userstore.md
Updates the essential parameters for the LDAP user store configuration
Resolves: https://github.com/wso2/micro-integrator/issues/1803
=> Update LDAP configurations

en/micro-integrator/docs/administer-and-observe/using-the-analytics-dashboard.md
Update code block language, java -> json.
Format json snippets to be consistent.
Remove unwanted white space.
https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/using-the-analytics-dashboard/#invoking-the-artifacts
=> Update code block to correct language, format json and remove white space

en/micro-integrator/docs/administer-and-observe/using-the-command-line-interface.md, en/micro-integrator/docs/administer-and-observe/working-with-management-api.md
Fixes https://github.com/wso2/micro-integrator/issues/1731
=> Add log resource changes to the Docs

en/micro-integrator/docs/use-cases/tutorials/exposing-several-services-as-a-single-service.md, en/micro-integrator/docs/use-cases/tutorials/file-processing.md, en/micro-integrator/docs/use-cases/tutorials/routing-requests-based-on-message-content.md, en/micro-integrator/docs/use-cases/tutorials/sending-a-simple-message-to-a-datasource.md, en/micro-integrator/docs/use-cases/tutorials/sending-a-simple-message-to-a-service.md, en/micro-integrator/docs/use-cases/tutorials/storing-and-forwarding-messages.md, en/micro-integrator/docs/use-cases/tutorials/transforming-message-content.md, en/micro-integrator/docs/use-cases/tutorials/using-inbound-endpoints.md, en/micro-integrator/docs/use-cases/tutorials/using-scheduled-tasks.md, en/micro-integrator/docs/use-cases/tutorials/using-templates.md, en/micro-integrator/docs/use-cases/tutorials/using-the-gmail-connector.md
Tutorial updates:
- Removed CLI
- Removed old project names
=> tutorial updates for new release

en/micro-integrator/docs/references/connectors/file-connector/file-connector-example.md
> This PR includes updated Windows file path.
=> Add windows source path

en/micro-integrator/docs/setup/installation/install_in_vm.md
This PR updates the installation doc on starting MI as a Windows Service
=> Update installation doc on starting MI as a Windows Service

en/micro-integrator/docs/administer-and-observe/using-the-command-line-interface.md
This is to correct the output file location of encrypted secrets
=> Correct the output file location

en/micro-integrator/docs/administer-and-observe/working-with-monitoring-dashboard.md
=> Add warning for Edge browser

en/micro-integrator/docs/use-cases/examples/rabbitmq_examples/point-to-point-rabbitmq.md
> Add point to point RabbitMQ sample.
=> Add point to point RabbitMQ sample.

en/home-page/docs/index.md
=> Update Streaming Integrator related links in the home page.

en/micro-integrator/docs/use-cases/examples/rabbitmq_examples/pub-sub-rabbitmq.md
> Add pub-sub rabbitMQ messaging sample.
=> Add pub-sub rabbitMQ messaging sample.

en/micro-integrator/docs/administer-and-observe/using-the-command-line-interface.md
This is to modify the user add command in docs
=> Modify user add command docs

en/micro-integrator/docs/administer-and-observe/working-with-management-api.md
Update management-API doc with enable/disable tracing resources.
Related doc issue https://github.com/wso2/micro-integrator/issues/1881
=> Update management-api docs with trace support

en/micro-integrator/docs/use-cases/examples/rabbitmq_examples/request-response-rabbitmq.md
> Add dual rabbitMQ dual channel docs.
=> Add dual rabbitMQ dual channel docs.

en/micro-integrator/docs/setup/databases/setting-up-MySQL.md
=> Change the mysql dbscript folder location

en/micro-integrator/docs/use-cases/examples/rabbitmq_examples/store-forward-rabbitmq.md
> Add rabbitMQ store and forward sample.
=> Add rabbitMQ store and forward sample.

en/micro-integrator/docs/setup/deployment/health_check.md, en/micro-integrator/mkdocs.yml
=> Add documentation for readiness probe

en/micro-integrator/docs/references/connectors/file-connector/file-connector-config.md
=> Add includeSubdirectories property

en/micro-integrator/docs/use-cases/examples/rabbitmq_examples/move-msgs-to-dlq-rabbitmq.md
=> Add RabbitMQ dlx sample.

en/micro-integrator/docs/use-cases/examples/rabbitmq_examples/requeue-msgs-with-errors-rabbitmq.md
=> Add rabbitMQ requeue docs.

en/micro-integrator/docs/develop/importing-projects.md
=> Update Project Import documentation

en/micro-integrator/docs/develop/creating-artifacts/data-services/creating-datasources.md
=> Update create datasource artifact doc

en/micro-integrator/docs/use-cases/examples/rabbitmq_examples/move-msgs-to-dlq-rabbitmq.md
Add rabbitMQ config command for rabbitMQ DLX
=> Add rabbitMQ config commands.

en/micro-integrator/docs/use-cases/examples/rabbitmq_examples/retry-delay-failed-msgs-rabbitmq.md
> Add rabbitMQ retry and delay sample.
=> Add rabbitMQ retry and delay sample.

en/micro-integrator/docs/develop/injecting-parameters.md
=> Add MI_HOME to conf path

en/micro-integrator/docs/administer-and-observe/using-the-analytics-dashboard.md, en/micro-integrator/docs/assets/attach/quick-start-guide/backend-service/HospitalServices-JDK11Proj/dependency-reduced-pom.xml, en/micro-integrator/docs/assets/attach/quick-start-guide/backend-service/HospitalServices-JDK11Proj/pom.xml, en/micro-integrator/docs/assets/attach/quick-start-guide/backend-service/HospitalServices-JDK11Proj/src/main/java/org/wso2/service/hospital/Application.java, en/micro-integrator/docs/assets/attach/quick-start-guide/backend-service/HospitalServices-JDK11Proj/src/main/java/org/wso2/service/hospital/DoctorTypeBean.java, en/micro-integrator/docs/assets/attach/quick-start-guide/backend-service/HospitalServices-JDK11Proj/src/main/java/org/wso2/service/hospital/GrandOakDoctorInfoService.java, en/micro-integrator/docs/assets/attach/quick-start-guide/backend-service/HospitalServices-JDK11Proj/src/main/java/org/wso2/service/hospital/HospitalService.java, en/micro-integrator/docs/assets/attach/quick-start-guide/backend-service/HospitalServices-JDK11Proj/src/main/java/org/wso2/service/hospital/PineValleyDoctorInfoService.java, en/micro-integrator/docs/use-cases/examples/rest_api_examples/transforming-content-type.md, en/micro-integrator/docs/use-cases/examples/rest_api_examples/using-get-with-a-body.md, en/micro-integrator/docs/use-cases/examples/rest_api_examples/using-post-with-no-body.md, en/micro-integrator/docs/use-cases/examples/rest_api_examples/using-post-with-query-param.md, en/micro-integrator/docs/use-cases/tutorials/exposing-several-services-as-a-single-service.md, en/micro-integrator/docs/use-cases/tutorials/routing-requests-based-on-message-content.md, en/micro-integrator/docs/use-cases/tutorials/sending-a-simple-message-to-a-service.md, en/micro-integrator/docs/use-cases/tutorials/storing-and-forwarding-messages.md, en/micro-integrator/docs/use-cases/tutorials/transforming-message-content.md, en/micro-integrator/docs/use-cases/tutorials/using-inbound-endpoints.md, en/micro-integrator/docs/use-cases/tutorials/using-templates.md, en/micro-integrator/docs/use-cases/tutorials/using-the-gmail-connector.md
This PR updates the DoctorInfo jar with JDK11 support and add relevant resources. Also, the previous Hospital-Service jar links, the command to run the jar are updated.
Updating the following links,
`https://github.com/wso2-docs/WSO2_EI/blob/master/Back-End-Service/Hospital-Service-2.0.0-EI7.jar`
to,
`https://github.com/wso2-docs/WSO2_EI/blob/master/Back-End-Service/Hospital-Service-JDK11-2.0.0.jar`
Updated the following command,
`java -jar Hospital-Service-2.0.0-EI7.jar`
to
`java -jar Hospital-Service-2.0.0-JDK11.jar`
=> Update Backend service jars with JDK 11 support

en/micro-integrator/docs/develop/integration-development-kickstart.md, en/micro-integrator/docs/overview/quick-start-guide.md
This PR updates the DoctorInfo jar, MI_QSG_HOME.zip with JDK11 support
=> Update DoctorInfo jar, QSG zip with JDK11 changes

en/micro-integrator/docs/administer-and-observe/logs/configuring_log4j_properties.md
This is to add the docs related to https://github.com/wso2/micro-integrator/pull/1737
=> Add system property to hide current_params

en/micro-integrator/docs/references/mediators/script-Mediator.md
Remove unwanted 'm' -> "using an inlinem "
https://ei.docs.wso2.com/en/latest/micro-integrator/references/mediators/script-Mediator/#configuration
=> Fix typo in Configuration section.

en/micro-integrator/docs/administer-and-observe/logs/configuring_log4j_properties.md
Minor updates to remove white space "log levels ." and apply consistent style to path.
https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/logs/configuring_log4j_properties/#setting-the-threshold
=> Remove white space and apply consistent style to path.

en/micro-integrator/docs/use-cases/examples/proxy_service_examples/securing-proxy-services.md
=> Update wsdl url

en/micro-integrator/docs/references/connectors/salesforce-connectors/sf-rest-connector-config.md
$subject for auth changes and two new operations fixing https://github.com/wso2/docs-ei/issues/1918
=> Reflect latest SF Rest connector changes in docs

en/micro-integrator/docs/develop/customizations/creating-custom-Inbound-endpoint.md
=> Update Creating a Custom Inbound Endpoint Doc

en/micro-integrator/docs/references/connectors/salesforce-soap-connector/salesforce-soap-reference.md
> This PR includes Salesforce SOAP reference documentation.
=> Add salesforcesoap reference doc

en/micro-integrator/docs/setup/deployment/deploying_wso2_ei.md
Fixes https://github.com/wso2/docs-ei/issues/1758
=> Update cluster docs

en/micro-integrator/docs/use-cases/tutorials/exposing-several-services-as-a-single-service.md
=> Add missing '$' sign

en/micro-integrator/docs/use-cases/examples/message_transformation_examples/json-to-soap-conversion.md, en/micro-integrator/docs/use-cases/examples/message_transformation_examples/pox-to-json-conversion.md
This PR updated message_transformation_examples doc with the relevant response payload, broken links.
=> Update message_transformation_examples doc

en/micro-integrator/docs/references/connectors/file-connector/file-connector-config.md
=> Changing the property name

en/micro-integrator/docs/references/connectors/salesforce-connectors/salesforce-soap-reference.md, en/micro-integrator/docs/references/connectors/salesforce-connectors/salesforcebulk-connector-configuration.md, en/micro-integrator/docs/references/connectors/salesforce-connectors/salesforcebulk-connector-example.md, en/micro-integrator/docs/references/connectors/salesforce-connectors/salesforcebulk-reference.md, en/micro-integrator/docs/references/connectors/salesforce-connectors/sf-soap-connector-config.md, en/micro-integrator/docs/references/connectors/salesforce-connectors/sf-soap-connector-example.md
> Update sf directory structure
=> Update sf directory structure

en/micro-integrator/docs/references/comparisong-mi7-ei6xx.md, en/micro-integrator/docs/setup/deployment/migrating-from-ei-6.x.x.md
=> Correct product version

en/micro-integrator/docs/setup/installation/install_prerequisites.md
=> Update compatibility docs

en/micro-integrator/docs/use-cases/tutorials/file-processing.md
=> Update screen shots

en/micro-integrator/docs/use-cases/examples/template_examples/using-sequence-templates.md
=> Update Using Sequence Templates Example

en/micro-integrator/docs/references/comparisong-mi7-ei6xx.md
=> Update comparison doc

en/streaming-integrator/docs/develop/streaming-integrator-studio-overview.md
=> Add a description for the Wizard View.

en/micro-integrator/docs/setup/deployment/migrating-from-ei-6.x.x.md
=> Update migration docs

en/micro-integrator/docs/use-cases/tutorials/exposing-several-services-as-a-single-service.md
=> Update Service Orchestration tutorial to Tooling 7.1.0

en/micro-integrator/docs/overview/introduction.md
=> Add monitoring tools to the introduction

en/micro-integrator/mkdocs.yml
=> Update yml file

en/micro-integrator/docs/setup/deployment/deployment_checklist.md, en/micro-integrator/mkdocs.yml
=> Improve Production Deployment Guidelines

en/micro-integrator/docs/references/connectors/bigquery-connector/bigquery-connector-example.md
> Removed API key from the sample.
=> Remove API key

en/micro-integrator/docs/setup/deployment/migrating-from-ei-6.x.x.md
=> Update migration doc

en/micro-integrator/docs/setup/deployment/migrating-from-ei-6.x.x.md
=> Update migration config section

en/micro-integrator/docs/setup/deployment/config-catalog-migration.md
Add Config catalog migration doc
=> Add Config catalog migration doc

en/micro-integrator/docs/setup/brokers/deploy-rabbitMQ.md
=> Add rabbitmq deployment docs

en/home-page/docs/index.md, en/streaming-integrator/docs/guides/performing-etl-tasks.md, en/streaming-integrator/mkdocs.yml
=> Add a separate guide for performing ETL.

en/micro-integrator/docs/references/connectors/as400-pcml-connector/as400-pcml-connector-reference.md
> This PR includes as400-pcml-connector reference documentation.
=> Add as400-pcml-connector reference doc

en/micro-integrator/docs/setup/installation/install_in_vm_installer.md
This is to update installer docs related to MI dashboard
=> Update installer doc

en/streaming-integrator/docs/ref/permission-apis.md
=> Add missing information in the Permission APIs.

en/micro-integrator/docs/setup/brokers/configure-with-rabbitMQ.md, en/micro-integrator/docs/use-cases/tutorials/storing-and-forwarding-messages.md
> Refactor RabbitMQ SSL config docs.
=> Refactor RabbitMQ SSL config docs.

en/streaming-integrator/docs/ref/business-Rules-APIs.md
=> Add missing information in the Business Rules APIs.

en/micro-integrator/docs/setup/brokers/deploy-rabbitMQ.md
=> update rabbitmq dep doc

en/micro-integrator/docs/develop/creating-artifacts/adding-connectors.md
Update add new connector doc to incorporate module related changes introduced in Integrations Studio Tooling 71.0
=> Update add new connector doc for tooling 7.1.0

en/micro-integrator/docs/references/connectors/salesforce-connectors/salesforce-soap-reference.md
> This PR includes Salesforce SOAP reference updated document.
=> Update Salesforce SOAP reference

en/streaming-integrator/docs/develop/streaming-integrator-studio-overview.md
=> Correct broken link.

en/micro-integrator/docs/setup/installation/run_in_containers.md
=> Update container dep docs

en/micro-integrator/docs/setup/deployment/deploying_wso2_ei.md
=> Remove irrelevant section link

en/micro-integrator/docs/develop/enabling-logs-for-api.md
=> Fix api log issue

en/micro-integrator/docs/setup/installation/install_in_vm_installer.md
=> Update installation doc

en/micro-integrator/docs/setup/installation/install_in_vm_installer.md
=> Update starting instructions for MI, Dashboard in windows

en/micro-integrator/docs/setup/installation/install_in_vm_installer.md
=> Change installation home directory for Mac

en/docs/index.md
=> Revert "versions - about this release 7.1.0 2"

en/docs/index.md
=> Revert "versions - about this release 7.1.0"

en/streaming-integrator/docs/examples/creating-etl-application-via-tooling.md
=> Add a "What's Next" section to the ETL Wizard tutorial.

en/streaming-integrator/docs/guides/performing-etl-tasks.md
=> Correct Typo.

en/micro-integrator/docs/setup/deployment/migrating-from-ei-7.0.x.md
=> Add internal api config migration content

en/streaming-integrator/mkdocs.yml
=> Remove Event Simulation APIs from the documentation navigator.

en/micro-integrator/docs/references/synapse-properties/inbound-endpoints/event-based-inbound-endpoints/rabbitmq-inbound-endpoint-properties.md
>Add RabbitMQ inbound endpoint related properties.
=> Add RabbitMQ inbound endpoint related properties.

en/micro-integrator/docs/setup/deployment/migrating-from-ei-6.x.x.md
=> Add configs to the migration doc

en/micro-integrator/docs/setup/deployment/deploying_in_kubernetes_with_helm.md, en/micro-integrator/docs/setup/deployment/ei_kubernetes_operator.md, en/micro-integrator/docs/setup/deployment/kubernetes_deployment.md, en/micro-integrator/mkdocs.yml
=> Add Helm setup document

en/micro-integrator/docs/setup/deployment/migrating-from-ei-6.x.x.md, en/micro-integrator/docs/setup/deployment/migrating-from-ei-7.0.x.md
=> (master branch) migrations doc fixes

en/micro-integrator/docs/administer-and-observe/using-the-command-line-interface.md, en/micro-integrator/docs/administer-and-observe/working-with-management-api.md
=> Update transaction counter docs

en/micro-integrator/docs/develop/advanced-development/using-swagger-for-apis.md, en/micro-integrator/docs/develop/enabling-logs-for-services.md, en/micro-integrator/docs/references/mediators/send-Mediator.md, en/micro-integrator/docs/setup/security/encrypting_plain_text.md, en/micro-integrator/docs/setup/security/securing_management_api.md
=> Update docs to remove inconsistent data

en/micro-integrator/docs/references/comparisong-mi7-ei6xx.md
=> Remove duplicate lines

en/home-page/docs/index.md, en/streaming-integrator/docs/examples/creating-etl-application-via-tooling.md, en/streaming-integrator/docs/examples/performing-real-time-etl-with-mysql.md, en/streaming-integrator/docs/guides/performing-etl-tasks.md, en/streaming-integrator/mkdocs.yml
=> Merge latest approved changes to the master branch

en/streaming-integrator/docs/examples/triggering-integrations-via-micro-integrator.md, en/streaming-integrator/docs/guides/triggering-integration-flows.md, en/streaming-integrator/docs/quick-start-guide/hello-world-with-mi.md
=> Add a note about the the gRPC endpoint type not being currently supported by the Integration Studio

en/micro-integrator/docs/references/connectors/develop-connectors.md
=> Update connector developer guide

en/micro-integrator/docs/develop/creating-unit-test-suite.md
=> Updating unit test creation documentation

en/micro-integrator/docs/develop/creating-unit-test-suite.md
=> Update unit testing documentation 

en/micro-integrator/docs/use-cases/examples/rest_api_examples/configuring-non-http-endpoints.md, en/micro-integrator/docs/use-cases/examples/rest_api_examples/handling-non-matching-resources.md, en/micro-integrator/docs/use-cases/examples/rest_api_examples/publishing-a-swagger-api.md, en/micro-integrator/docs/use-cases/examples/rest_api_examples/securing-rest-apis.md, en/micro-integrator/docs/use-cases/examples/rest_api_examples/setting-https-status-codes.md, en/micro-integrator/docs/use-cases/examples/rest_api_examples/setting-query-params-outgoing-messages.md, en/micro-integrator/docs/use-cases/examples/rest_api_examples/transforming-content-type.md, en/micro-integrator/docs/use-cases/examples/rest_api_examples/using-post-with-no-body.md, en/micro-integrator/docs/use-cases/examples/rest_api_examples/using-post-with-query-param.md
This PR updates the rest_api_examples documentation
=> Update rest_api_examples documentation

en/streaming-integrator/mkdocs.yml
=> Update navigator link

en/micro-integrator/docs/use-cases/examples/rest_api_examples/transforming-content-type.md
=> Update a typo

en/micro-integrator/docs/setup/deployment/k8s-pipeline/adding-test-cases.md, en/micro-integrator/docs/setup/deployment/k8s-pipeline/deploy-your-own-artifact.md, en/micro-integrator/docs/setup/deployment/k8s-pipeline/modifying-product-configurations.md
> Changing the inner relative links in three files committed.
> To make the user experience a flawless one with no broken links or page not found scenarios.
=> Add the inner relative links 

en/streaming-integrator/docs/samples/CDCWithPollingMode.md
=> Add MongoDB as supported database type in CDC sample

en/streaming-integrator/docs/samples/CDCWithPollingMode.md
Reverts wso2/docs-ei#2148 to investigate build break.
=> Revert "Add MongoDB as supported database type in CDC sample"

en/streaming-integrator/docs/samples/CDCWithPollingMode.md
Reverts wso2/docs-ei#2151.
Restoring the original PR, as the build is resolved.
=> Revert "Revert "Add MongoDB as supported database type in CDC sample""

en/micro-integrator/docs/setup/deployment/k8s-pipeline/deploy-your-own-artifact.md, en/micro-integrator/docs/setup/deployment/k8s-pipeline/testing-the-pipeline-environment.md
> Clearing relative link issues found during reviews.
=> Changing link references

en/micro-integrator/docs/setup/deployment/k8s-pipeline/quick-start-guide.md
> Install Pipeline code block was not displaying made changes to show it.
> Install Pipeline code block is displayed.
=> Fix code block visibility

en/micro-integrator/docs/setup/install_and_setup_overview.md
=> Add performance results to the docs

en/micro-integrator/docs/references/connectors/kafka-connector/kafka-connector-config.md
> Add connection pool parameters to the docs.
=> Add connection pool parameters

en/micro-integrator/docs/references/mediators/cache-Mediator.md
Currently the **Example 1** of Cache mediator is an example for how Cache mediator does not work. This PR will re order the samples, and provide a working example as **Example 1**
https://ei.docs.wso2.com/en/7.1.0/micro-integrator/references/mediators/cache-Mediator/
=> Reorder cache mediator examples and improve them

en/streaming-integrator/docs/setup/installing-as-windows-service.md, en/streaming-integrator/docs/setup/installing-si-binary.md, en/streaming-integrator/docs/setup/installing-si-in-vm.md, en/streaming-integrator/mkdocs.yml
=> Update documentation on Installing SI

en/micro-integrator/docs/administer-and-observe/cloud-native-observability-dashboards.md, en/micro-integrator/docs/setup/observability/setting-up-minimum-basic-observability-deployment.md, en/streaming-integrator/docs/overview/overview.md, en/streaming-integrator/mkdocs.yml
=> Add information about monitoring EI statistics with Grafana

en/streaming-integrator/docs/overview/overview.md, en/streaming-integrator/docs/quick-start-guide/quick-start-guide.md, en/streaming-integrator/docs/setup/installing-as-windows-service.md, en/streaming-integrator/docs/setup/installing-si-binary.md, en/streaming-integrator/docs/setup/installing-si-in-vm.md, en/streaming-integrator/mkdocs.yml
=> Update SI Installation documentation

docs-ei.iml, en/streaming-integrator/docs/quick-start-guide/quick-start-guide.md, en/streaming-integrator/docs/setup/installing-si-in-vm.md, en/streaming-integrator/mkdocs.yml
=> Fix typo and correct broken links

en/streaming-integrator/docs/guides/fault-Handling.md
=> Correct spelling

en/micro-integrator/docs/administer-and-observe/cloud-native-observability-dashboards.md, en/micro-integrator/docs/setup/observability/setting-up-minimum-basic-observability-deployment.md
=> Update Observability Solution documentation

en/micro-integrator/docs/setup/security/securing_management_api.md
Replacing https://github.com/wso2/docs-ei/pull/2159
=> minor fix in management API doc

en/home-page/theme/material/partials/header.html, en/micro-integrator/theme/material/partials/header.html, en/streaming-integrator/theme/material/partials/header.html
Applying banner to master documentation.
=> WIP banner for the master

en/micro-integrator/docs/setup/observability/setting-up-classic-observability-deployment.md, en/micro-integrator/mkdocs.yml
=> Update Observability Solution documentation.

en/micro-integrator/mkdocs.yml
=> Update Observability Solution documentation navigator.

en/micro-integrator/docs/setup/observability/observability-and-manage-overview.md, en/micro-integrator/docs/setup/observability/observability-overview.md, en/micro-integrator/mkdocs.yml
=> Update Observability Solution documentation navigator links.

en/micro-integrator/docs/administer-and-observe/cloud-native-observability-dashboards.md, en/micro-integrator/docs/setup/observability/setting-up-cloud-native-observability-in-kubernetes.md, en/micro-integrator/docs/setup/observability/setting-up-minimum-basic-observability-deployment.md
=> Format code block

en/micro-integrator/docs/setup/deployment/migrating-from-ei-6.x.x.md, en/micro-integrator/docs/setup/deployment/migrating-from-ei-7.0.x.md, en/micro-integrator/docs/setup/deployment/migrating-from-esb-5.x.x.md
=> Add password decryption to migration docs.

en/micro-integrator/docs/overview/quick-start-guide.md
=> Revert "Update quick-start-guide.md"

en/streaming-integrator/docs/quick-start-guide/quick-start-guide.md
> Rewrite the Streaming Integrator quick start guide to indicate how WSO2 SI addresses the needs of the target users such as Streaming Integration, ETL, CDC, etc. It currently highlights mainly the stream processing abilities of the product.
> Write the quick start guide around a scenario where the Streaming Integrator captures change data from a file, does a Math operation and publishes the output to a Kafka topic, providing access to streaming data to client applications that are not capable of reading streaming data.
- …
=> Rewrite the Streaming Integrator Quick Start Guide.

en/micro-integrator/docs/setup/dynamic_server_configurations.md
=> (7.1.0 branch) copy edit

en/micro-integrator/docs/overview/about-this-release-7.1.0.md, en/micro-integrator/docs/setup/deployment/migrating-from-esb-5.x.x.md, en/micro-integrator/docs/setup/user_stores/managing_users.md, en/micro-integrator/docs/setup/user_stores/setting_up_a_userstore.md
=> (master branch) Migration updates master

en/micro-integrator/docs/overview/about-this-release-7.1.0.md, en/micro-integrator/docs/setup/deployment/migrating-from-esb-5.x.x.md, en/micro-integrator/docs/setup/user_stores/managing_users.md, en/micro-integrator/docs/setup/user_stores/setting_up_a_userstore.md
=> (7.1.0 branch) migration updates to 7.1.0

en/micro-integrator/docs/setup/user_stores/managing_users.md, en/micro-integrator/docs/setup/user_stores/setting_up_a_userstore.md
migration - copy edits and updated procedures.
=> (7.1.0 branch) Fix migration 7.1.0

en/micro-integrator/docs/develop/troubleshooting-WSO2-Integration-Studio.md
Add information on Firefox browser issues to the Integration Studio troubleshooting page.
=> Add troubleshooting information

en/streaming-integrator/docs/ref/performance-analysis-results.md
=> Update the Streaming Integrator Performance Statistics

en/micro-integrator/docs/references/mediators/property-reference/generic-Properties.md, en/micro-integrator/docs/references/synapse-properties/inbound-endpoints/event-based-inbound-endpoints/rabbitmq-inbound-endpoint-properties.md, en/micro-integrator/docs/references/synapse-properties/transport-parameters/rabbitmq-transport-parameters.md
Fixes https://github.com/wso2/docs-ei/issues/1741
=> (7.1.0 branch) Rabbitmq parameters 7.1.0

en/micro-integrator/docs/references/mediators/property-reference/generic-Properties.md
Removed references to 'Inbound Endpoint' in the SET_ROLLBACK_ONLY and SET_REQUEUE_ON_ROLLBACK properties.
=> removed 'Inbound Endpoint' specifics

en/micro-integrator/docs/develop/installing-WSO2-Integration-Studio.md
Adds Integration Studio download and install instructions for Windows users.
=> Add Windows installation instructions

en/micro-integrator/docs/administer-and-observe/working-with-monitoring-dashboard.md
Added a note about the user store configuration requirements for the dashboard.
=> (7.1.0 branch) user store details for the dashboard

en/micro-integrator/docs/administer-and-observe/working-with-monitoring-dashboard.md, en/micro-integrator/docs/setup/databases/setting-up-IBM-DB2.md, en/micro-integrator/docs/setup/databases/setting-up-MSSQL.md, en/micro-integrator/docs/setup/databases/setting-up-MySQL.md, en/micro-integrator/docs/setup/databases/setting-up-Oracle.md, en/micro-integrator/docs/setup/databases/setting-up-PostgreSQL.md, en/micro-integrator/docs/setup/deployment/deploying_wso2_ei.md, en/micro-integrator/docs/setup/pull/PULL-CONTENT-user-store-db-id.md, en/micro-integrator/docs/setup/user_stores/setting_up_a_userstore.md
Improving the description about how and when to use the `[realm_manager]` toml configuration.
=> (7.1.0 branch) improving realm_manager configuration description

en/micro-integrator/docs/references/config-catalog.md, en/micro-integrator/docs/references/connectors/amazons3-connector/amazons3-connector-example.md, en/micro-integrator/docs/references/connectors/documentum/documentum-example.md, en/micro-integrator/docs/references/connectors/documentum/documentum-overview.md, en/micro-integrator/docs/references/connectors/documentum/documentum-reference.md, en/micro-integrator/docs/references/connectors/google-pubsub-connector/googlepubsub-connector-example.md, en/micro-integrator/mkdocs.yml
Documentation for Documentum connector.
=> Documentum Connector docs

en/micro-integrator/docs/references/connectors/amazons3-connector/amazons3-connector-example.md
Removes content type parameter from init as per https://github.com/wso2/docs-ei/issues/2140
=> Fix AmazonS3 Config

en/micro-integrator/docs/references/connectors/why-connectors.md
Fixes links to Whats New section in "When to use Connectors" doc.
=> Fix connector doc links

en/micro-integrator/docs/references/synapse-properties/transport-parameters/hl7-transport-parameters.md, en/micro-integrator/docs/setup/transport_configurations/configuring-transports.md, en/micro-integrator/mkdocs.yml
Committing draft content about HL7 transport.
=> (master branch) Add hl7docs 7.1.0

en/streaming-integrator/docs/quick-start-guide/getting-started/getting-started-guide-overview.md
=> Apply missing line breaks

en/micro-integrator/docs/references/synapse-properties/transport-parameters/hl7-transport-parameters.md, en/micro-integrator/docs/setup/deployment/migrating-from-ei-6.x.x.md, en/micro-integrator/docs/setup/deployment/migrating-from-ei-7.0.x.md, en/micro-integrator/docs/setup/deployment/migrating-from-esb-5.x.x.md, en/micro-integrator/docs/setup/transport_configurations/configuring-transports.md
=> Update Hl7 related docs

en/micro-integrator/docs/references/synapse-properties/transport-parameters/hl7-transport-parameters.md, en/micro-integrator/docs/setup/deployment/migrating-from-ei-6.x.x.md, en/micro-integrator/docs/setup/deployment/migrating-from-ei-7.0.x.md, en/micro-integrator/docs/setup/deployment/migrating-from-esb-5.x.x.md, en/micro-integrator/docs/setup/transport_configurations/configuring-transports.md
=> Update hl7 docs

en/micro-integrator/docs/references/synapse-properties/transport-parameters/hl7-transport-parameters.md
=> Fix formatting

en/micro-integrator/docs/references/synapse-properties/transport-parameters/hl7-transport-parameters.md, en/micro-integrator/docs/setup/deployment/migrating-from-ei-6.x.x.md, en/micro-integrator/docs/setup/deployment/migrating-from-ei-7.0.x.md, en/micro-integrator/docs/setup/deployment/migrating-from-esb-5.x.x.md, en/micro-integrator/docs/setup/transport_configurations/configuring-transports.md, en/micro-integrator/mkdocs.yml
=> [7.1.0] Add Hl7 Docs

en/micro-integrator/docs/overview/introduction.md
=> Broken image

en/micro-integrator/docs/references/mediators/dB-Report-Mediator.md
Added note to DB report mediator regarding json-eval expression.
=> Update DB report mediator

en/streaming-integrator/docs/examples/performing-real-time-etl-with-mysql.md, en/streaming-integrator/docs/guides/extracting-data-from-static-sources-in-real-time.md
=> Add the Extracting Data from Static Sources guide

en/streaming-integrator/docs/guides/extracting-data-from-static-sources-in-real-time.md
=> Update the Extracting Data from Static Sources guide

en/micro-integrator/docs/references/mediators/property-reference/axis2-properties.md, en/micro-integrator/docs/references/synapse-properties/transport-parameters/hl7-transport-parameters.md, en/micro-integrator/docs/setup/transport_configurations/configuring-transports.md, en/micro-integrator/docs/use-cases/examples/hl7-examples/HL7_message_store.md, en/micro-integrator/docs/use-cases/examples/hl7-examples/HL7_proxy_service.md, en/micro-integrator/docs/use-cases/examples/hl7-examples/acknowledge_hl7_messages.md, en/micro-integrator/mkdocs.yml
=> (master branch) HL7 examples and parameters

en/micro-integrator/docs/references/connectors/kafka-connector/kafka-connector-config.md, en/micro-integrator/docs/references/connectors/kafka-connector/kafka-connector-producer-example.md, en/micro-integrator/docs/references/connectors/kafka-connector/kafka-inbound-endpoint-example.md, en/micro-integrator/docs/references/connectors/kafka-connector/setting-up-kafka.md
=> Update Kafka docs

en/streaming-integrator/docs/guides/extracting-data-from-static-sources-in-real-time.md
=> Correct subtitle

en/micro-integrator/docs/references/connectors/documentum/documentum-example.md
Updated the create document usage in example
> Link(s) to product documentation that addresses the changes of this PR. If no …
=> Adding Create Document Content

en/micro-integrator/docs/references/connectors/documentum/documentum-reference.md
Updating for sample request
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …
=> Folder Description 

en/micro-integrator/docs/references/connectors/documentum/documentum-reference.md
Included brief description to every fields.
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
=> updated reference document

en/home-page/mkdocs.yml, en/micro-integrator/mkdocs.yml, en/streaming-integrator/mkdocs.yml
Changes the site URL to '7.2.0' in the master branche.
This is expected to help SEO.
=> (master branch) site url of master updated

en/streaming-integrator/docs/guides/extracting-data-from-static-sources-in-real-time.md
=> Correct formatting issue

en/streaming-integrator/docs/guides/extracting-data-from-static-sources-in-real-time.md, en/streaming-integrator/docs/guides/receiving-data-in-transit.md
=> Add content on Receiving data from push sources

en/streaming-integrator/docs/guides/extracting-data-from-static-sources-in-real-time.md
=> Update documentation on extracting data from cloud storages

en/streaming-integrator/docs/guides/receiving-data-in-transit.md
=> Update documentation on receiving data from pull sources.

en/micro-integrator/docs/setup/deployment/migrating-from-ei-6.x.x.md, en/micro-integrator/docs/setup/deployment/migrating-from-esb-5.x.x.md
=> Fix migration issues 7.1.0

en/micro-integrator/docs/develop/intro-integration-development.md
updated the 'Develop' landing page to include the key topics.
=> (7.1.0 branch) Deploy landing page

en/micro-integrator/docs/develop/intro-integration-development.md
updated the 'Develop' landing page to include the key topics.
=> (master branch) develop landing page updated

en/micro-integrator/docs/references/mediators/data-Mapper-Mediator.md
=> (7.1.0 branch) note about AI data mapper

en/micro-integrator/docs/references/mediators/property-reference/axis2-properties.md
Changed erroneous 'parameter' tag to 'property'
=> Changed erroneous 'parameter' tag to 'property'

en/streaming-integrator/docs/guides/receiving-data-in-transit.md
=> [SI Docs] Correct SI guides based on review comments

en/streaming-integrator/docs/guides/extracting-data-from-static-sources-in-real-time.md, en/streaming-integrator/docs/guides/loading-and-writing-date.md, en/streaming-integrator/docs/guides/receiving-data-in-transit.md
=> [SI Docs] Add links to Siddhi mappers in SI guides

en/micro-integrator/docs/develop/using-remote-micro-integrator.md
Fixes https://github.com/wso2/docs-ei/issues/1610
=> (7.1.0 branch) Disabling graceful shutdown for development

en/micro-integrator/docs/develop/using-remote-micro-integrator.md
Fixes https://github.com/wso2/docs-ei/issues/1610
=> (master branch) Disabling graceful shutdown for development

en/streaming-integrator/docs/guides/handling-errors.md
=> Fix image links

en/micro-integrator/docs/references/mediators/call-Template-Mediator.md, en/micro-integrator/docs/references/synapse-properties/template-properties.md, en/micro-integrator/docs/use-cases/examples/template_examples/using-sequence-templates.md
Fixes https://github.com/wso2/docs-ei/issues/1701
Document mandatory and default parameters for sequence template
=> (7.1.0 branch) mandatory and default parameters for sequence template

en/micro-integrator/docs/references/connectors/amazons3-connector/1.x/amazons3-connector-config.md, en/micro-integrator/docs/references/connectors/amazons3-connector/1.x/amazons3-connector-example.md, en/micro-integrator/docs/references/connectors/amazons3-connector/1.x/amazons3-connector-overview.md, en/micro-integrator/docs/references/connectors/amazons3-connector/2.x/amazons3-connector-config.md, en/micro-integrator/docs/references/connectors/amazons3-connector/2.x/amazons3-connector-example.md, en/micro-integrator/docs/references/connectors/amazons3-connector/2.x/amazons3-connector-overview.md
=> Fix the img path issue

en/streaming-integrator/docs/guides/processing-data.md
=> Add information about cleansing data to the Processing Data guide

en/micro-integrator/docs/references/config-catalog.md
=> Fix blocking builders and formatters

en/streaming-integrator/docs/guides/processing-data.md
=> Add information about transforming data to the Processing Data guide

en/micro-integrator/docs/references/mediators/enrich-Mediator.md
Add JSON enriching examples for the Enrich Mediator
=> Add JSON enriching examples

en/micro-integrator/docs/administer-and-observe/using-the-analytics-dashboard.md
Modify analytics docs to mention new EI Analytics distribution
=> Modify analytics docs to mention new ei analytics pack

en/streaming-integrator/docs/guides/processing-data.md
=> Add information about enriching data to the Processing Data guide

en/micro-integrator/docs/references/mediators/data-Mapper-Mediator.md
=> (master branch) Add datamapper note master

en/micro-integrator/docs/references/mediators/call-Template-Mediator.md, en/micro-integrator/docs/references/synapse-properties/template-properties.md, en/micro-integrator/docs/use-cases/examples/template_examples/using-sequence-templates.md
Fixes #1701
Document mandatory and default parameters for sequence template
=> (master branch) mandatory and default parameters for sequence template

en/streaming-integrator/docs/admin/managing-grafana-dashboards.md, en/streaming-integrator/docs/admin/monitoring-si-performance-via-grafana.md, en/streaming-integrator/docs/admin/monitoring-the-streaming-integrator.md, en/streaming-integrator/docs/admin/setting-up-grafana-dashboards.md, en/streaming-integrator/docs/examples/creating-etl-application-via-tooling.md, en/streaming-integrator/docs/examples/resources/dashboards/Siddhi Aggregation Statistics-1580285366634.json, en/streaming-integrator/docs/examples/resources/dashboards/Siddhi On-Demand Query Statistics-1580285396455.json, en/streaming-integrator/docs/examples/resources/dashboards/Siddhi Overall Statistics-1580282204141.json, en/streaming-integrator/docs/examples/resources/dashboards/Siddhi Query Statistics-1580282256683.json, en/streaming-integrator/docs/examples/resources/dashboards/Siddhi Server Statistics-1580282223378.json, en/streaming-integrator/docs/examples/resources/dashboards/Siddhi Sink Statistics-1580285225995.json, en/streaming-integrator/docs/examples/resources/dashboards/Siddhi Source Statistics-1580285208526.json, en/streaming-integrator/docs/examples/resources/dashboards/Siddhi Stream Statistics-1580282240055.json, en/streaming-integrator/docs/examples/resources/dashboards/Siddhi Table Statistics-1580285249969.json, en/streaming-integrator/docs/examples/resources/dashboards/Siddhi Trigger Statistics-1580285383360.json, en/streaming-integrator/docs/examples/resources/dashboards/Siddhi Window Statistics-1580285269330.json, en/streaming-integrator/docs/guides/performing-etl-tasks.md, en/streaming-integrator/docs/guides/processing-data.md, en/streaming-integrator/docs/guides/viewing-dashboards.md, en/streaming-integrator/docs/quick-start-guide/getting-started/monitor-statistics.md, en/streaming-integrator/mkdocs.yml
=> Add information about Monitoring the Streaming Integrator via Grafana

en/micro-integrator/docs/references/mediators/enrich-Mediator.md, en/micro-integrator/docs/references/mediators/payloadFactory-Mediator.md, en/micro-integrator/docs/references/mediators/property-Mediator.md, en/micro-integrator/docs/use-cases/examples/json_examples/json-examples.md
> New JSON type for property
Enrich remove for JSON properties
Evaluating JSONPath against property
=> Add documentation changes for JSON improvements.

en/micro-integrator/docs/setup/user_stores/managing_users.md
=> (7.1.0 branch) fix typo

en/micro-integrator/docs/setup/user_stores/managing_users.md
=> (master branch) fix typo

en/micro-integrator/docs/administer-and-observe/using-the-analytics-dashboard.md
fixing a broken image.
Only applicable to the 7.1.0 branch.
=> (7.1.0 branch) fixing broken image

en/micro-integrator/docs/setup/security/configuring_keystores.md
=> (7.1.0 branch) broken link and typos

en/micro-integrator/docs/setup/security/configuring_keystores.md
Merging https://github.com/wso2/docs-ei/pull/2468 to the master.
=> (master branch) updates to configuring keystores

en/streaming-integrator/docs/admin/creating-business-rules-templates.md
=> Correct the URL to access Business Rules mentioned in documentation

en/streaming-integrator/docs/admin/creating-business-rules-templates.md
=> Revert "Correct the URL to access Business Rules mentioned in documentation"

en/streaming-integrator/docs/quick-start-guide/getting-started/monitor-statistics.md, en/streaming-integrator/docs/quick-start-guide/quick-start-guide.md, en/streaming-integrator/docs/setup/installing-as-a-windows-service.md, en/streaming-integrator/docs/setup/installing-si-binary.md, en/streaming-integrator/docs/setup/installing-si-in-vm.md, en/streaming-integrator/docs/setup/installing-si-using-docker.md, en/streaming-integrator/docs/setup/installing-si-using-kubernetes.md, en/streaming-integrator/mkdocs.yml
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
=> Fix the broken navigator links and add a new link in the quick start guide.

en/streaming-integrator/docs/samples/PublishKafkaInAvroFormatUsingSchemaRegistry.md
=> Format sample document

en/streaming-integrator/docs/ref/siddhi-Application-Management-APIs.md, en/streaming-integrator/docs/setup/deploying-si-as-minimum-ha-cluster.md
=> Add documentation on HA node states REST API

en/streaming-integrator/docs/samples/PublishKafkaInAvroFormatUsingSchemaRegistry.md
=> Test sample document and add tip to make it clearer

en/streaming-integrator/docs/samples/PublishKafkaInAvroFormatUsingSchemaRegistry.md
To address Git issue [1].
[1] https://github.com/wso2/docs-ei/issues/1639
=> Add descriptions to explain how the Avro schema is applied to streaming events in sample document

en/streaming-integrator/docs/quick-start-guide/hello-world-with-mi.md, en/streaming-integrator/docs/samples/PublishKafkaInAvroFormatUsingSchemaRegistry.md, en/streaming-integrator/docs/samples/ReceivePrometheusMetrics.md
=> Format Streaming Integrator sample document

en/streaming-integrator/docs/samples/PublishKafkaInAvroFormatUsingSchemaRegistry.md, en/streaming-integrator/docs/samples/ReceivePrometheusMetrics.md
=> Correct formatting errors

en/streaming-integrator/docs/guides/extracting-data-from-static-sources-in-real-time.md
=> Remove incomplete section

en/micro-integrator/docs/administer-and-observe/logs/masking_sensitive_info_in_logs.md
This PR updates the masking sensitive info documentation. 
Related PR: https://github.com/wso2-support/micro-integrator/pull/74
=> Update masking sensitive info documentation

en/micro-integrator/docs/references/connectors/amazons3-connector/1.x/amazons3-connector-1.x-example.md
=> (7.1.0 branch ) Amazon S3 connector broken links

en/micro-integrator/docs/references/connectors/file-connector/file-connector-example.md
=> (7.1.0 branch) File connector image resize

en/micro-integrator/docs/administer-and-observe/logs/masking_sensitive_info_in_logs.md
=> (7.1.0 branch) heading and anchor updated

en/streaming-integrator/docs/admin/user-Management-via-the-IdP-Client-Interface.md, en/streaming-integrator/docs/admin/user-management.md
=> Change "Stream Processor" to "Streaming Integrator" in User Management Documentation

en/micro-integrator/docs/administer-and-observe/logs/configuring_log4j_properties.md, en/micro-integrator/docs/administer-and-observe/logs/enabling_component_logs.md, en/micro-integrator/docs/administer-and-observe/logs/monitoring_logs.md, en/micro-integrator/mkdocs.yml
=> (7.1.0 branch) Log monitoring 7.1.0

en/micro-integrator/docs/administer-and-observe/working-with-monitoring-dashboard.md
=> (7.1.0 branch) dashboard sign in prerequisite

en/streaming-integrator/docs/ref/performance-analysis-results.md
=> Complete Performance Analysis Summary

en/micro-integrator/docs/administer-and-observe/using-the-analytics-dashboard.md, en/micro-integrator/docs/setup/observability/setting-up-classic-observability-deployment.md
Updates that were identified while testing the Classical Observability (EI Analytics solution).
=> (7.1.0 branch) Tested and updated Classical Observability solution

en/micro-integrator/docs/develop/creating-artifacts/creating-an-api.md
=> (7.1.0 branch) creating restapi doc fixes

en/micro-integrator/docs/develop/creating-artifacts/creating-an-api.md
=> (master branch) creating rest api bugs

en/streaming-integrator/docs/admin/monitoring-received-events-count-via-logs.md, en/streaming-integrator/mkdocs.yml
=> Add documentation for the Received Event Count Logger

en/micro-integrator/docs/develop/creating-artifacts/data-services/creating-data-services.md, en/micro-integrator/docs/use-cases/examples/data_integration/mongo-data-service.md, en/micro-integrator/docs/use-cases/learn-overview.md, en/micro-integrator/mkdocs.yml
=> (7.1.0 branch) added mongodb data service example

en/micro-integrator/docs/develop/creating-artifacts/data-services/creating-data-services.md
Substituted "SOAP" for "REST" in the last example that actually refers on how to expose the Data Service as a REST operation
=> Substituted "SOAP" for "REST" in the last example.

en/streaming-integrator/docs/guides/use-cases.md, en/streaming-integrator/docs/quick-start-guide/hello-world-with-mi.md
To correct https://github.com/wso2/docs-ei/issues/2276
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
=> Add missing step in the QSG to run SI with MI

en/streaming-integrator/docs/examples/triggering-integrations-via-micro-integrator.md, en/streaming-integrator/docs/quick-start-guide/hello-world-with-mi.md
> To correct https://github.com/wso2/docs-ei/issues/1009.
=> Add missing step in the tutorial to run SI with MI

en/streaming-integrator/docs/overview/overview.md
=> Update links in the Overview page

en/streaming-integrator/docs/setup/installing-si-using-kubernetes.md
To correct https://github.com/wso2/docs-ei/issues/2178
=> Correct formatting error

en/streaming-integrator/mkdocs.yml
=> Correct allignment issue in Streaming Integrator documentation navigator

en/streaming-integrator/mkdocs.yml
=> Revert "Correct allignment issue in Streaming Integrator documentation navigator"

en/micro-integrator/docs/develop/advanced-development/applying-security-to-a-proxy-service.md
remove content on role-based security from Proxy Service doc.
=> (7.1.0 branch) remove content about role-based security

en/micro-integrator/docs/develop/advanced-development/applying-security-to-a-proxy-service.md
hide content on role-based security from Proxy Service doc.
=> (master branch) remove content about role-based security

en/micro-integrator/docs/use-cases/examples/file-processing/mailto-transport-examples.md
=> Fix https://github.com/wso2/docs-ei/issues/1681

en/micro-integrator/docs/setup/deployment/deploying_wso2_ei.md
Fixes https://github.com/wso2/docs-ei/issues/2543
=> Elaborate on task resolvers

en/micro-integrator/docs/references/connectors/file-connector/file-connector-example.md
> Resolves: https://github.com/wso2/docs-ei/issues/1778 …
=> Change the correct file name

en/micro-integrator/docs/setup/deployment/deploying_wso2_ei.md
Fixes https://github.com/wso2/docs-ei/issues/2543
=> Elaborate more on Task Resovlers

en/micro-integrator/docs/references/mediators/cache-Mediator.md
Fixes https://github.com/wso2/docs-ei/issues/1509
=> Update cache mediator doc

en/micro-integrator/docs/setup/transport_configurations/configuring-transports.md
Fix https://github.com/wso2/docs-ei/issues/97
=> Add custom transport docs

en/micro-integrator/docs/setup/transport_configurations/configuring-transports.md
Fix https://github.com/wso2/docs-ei/issues/97
=> Add custom transport config docs

en/micro-integrator/docs/references/connectors/salesforce-connectors/sf-rest-connector-config.md
> Resolves: https://github.com/wso2/docs-ei/issues/1707 …
=> Add doc for missing operation

en/micro-integrator/docs/setup/changing_default_ports.md
> $subject. Resolves #2530.
- https://github.com/wso2/docs-ei/pull/2562
- https://github.com/wso2/docs-ei/pull/2576
=> Add information on default analytics ports

en/micro-integrator/docs/use-cases/examples/endpoint_examples/using-static-recepient-list-endpoints.md
Related to #2352
Porting #2575
=> [7.0.0] Add a WIP note for not working sample

en/micro-integrator/docs/use-cases/examples/endpoint_examples/using-static-recepient-list-endpoints.md
Related to #2352
Porting https://github.com/wso2/docs-ei/pull/2575
=> Add a WIP note for not working sample

en/micro-integrator/docs/references/mediators/property-reference/axis2-properties.md, en/micro-integrator/docs/use-cases/examples/endpoint_examples/mtom-swa-with-endpoints.md
Fixes https://github.com/wso2/docs-ei/issues/2461
=> Add info about DECODE_MULTIPART_DATA property

en/micro-integrator/docs/setup/security/encrypting_plain_text.md
> $subject. Resolves https://github.com/wso2/docs-ei/issues/1591
=> Provide sample of encrypting secrets defined in a properties file

en/micro-integrator/docs/use-cases/examples/endpoint_examples/using-failover-endpoints.md
Fix https://github.com/wso2/docs-ei/issues/2439
=> Failover endpoint TOML docs

.gitignore, en/micro-integrator/docs/references/synapse-properties/inbound-endpoints/event-based-inbound-endpoints/rabbitmq-inbound-endpoint-properties.md
> Resolves: https://github.com/wso2/docs-ei/issues/2154 …
=> Move the exchange name to optional params

en/micro-integrator/docs/use-cases/examples/rest_api_examples/using-get-with-a-body.md
Resolves https://github.com/wso2/docs-ei/issues/1750
=> [7.1.0] Delete unnecessary wordings in Handling GET message with no-body

en/micro-integrator/docs/references/config-catalog.md, en/micro-integrator/tools/config-catalog-generator/data/_custom-transport-listener.toml, en/micro-integrator/tools/config-catalog-generator/data/_custom-transport-sender.toml, en/micro-integrator/tools/config-catalog-generator/data/configs.json, en/micro-integrator/tools/config-catalog-generator/dist/config-catalog.md
Updated parameters for custom transports.'
Fixes https://github.com/wso2/docs-ei/issues/97
=> (7.1.0 branch) custom transport configs

en/micro-integrator/docs/references/mediators/class-Mediator.md
> Resolves: https://github.com/wso2/docs-ei/issues/2387 …
=> Add a note regarding the class mediator property

en/micro-integrator/docs/use-cases/examples/rest_api_examples/using-get-with-a-body.md
Resolves https://github.com/wso2/docs-ei/issues/1750
Porting https://github.com/wso2/docs-ei/pull/2602
=> Delete unnecessary wordings in Handling GET message with no-body

en/micro-integrator/docs/references/synapse-properties/endpoint-properties.md
Fixes #2199 
**Related PRs**
#2598 
#2597
=> Format endpoint properties - Fix #2199

en/micro-integrator/docs/references/synapse-properties/endpoint-properties.md
=> [7.1.0] Format endpoint properties - Fix #2199

en/micro-integrator/docs/references/synapse-properties/endpoint-properties.md
=> [7.0.0] Format endpoint properties - Fix #2199

en/micro-integrator/docs/references/config-catalog.md, en/micro-integrator/tools/config-catalog-generator/data/_custom-transport-listener.toml, en/micro-integrator/tools/config-catalog-generator/data/_custom-transport-sender.toml, en/micro-integrator/tools/config-catalog-generator/data/configs.json, en/micro-integrator/tools/config-catalog-generator/dist/config-catalog.md
Fixes https://github.com/wso2/docs-ei/issues/97
=> formatting fix

en/micro-integrator/docs/setup/transport_configurations/multi-https-transport.md
Fixes https://github.com/wso2/docs-ei/issues/2488
=> Add note about DNS lookup latencies in custom ssl profiles

en/micro-integrator/docs/develop/create-docker-project.md, en/micro-integrator/docs/develop/create-kubernetes-project.md, en/micro-integrator/docs/setup/deployment/k8s-samples/content-based-routing.md, en/micro-integrator/docs/setup/deployment/k8s-samples/hello-world.md, en/micro-integrator/docs/setup/deployment/k8s-samples/jms-sender-receiver.md
Fixes: https://github.com/wso2/docs-ei/issues/1798
=> (7.1.0 branch) Note about docker build

en/micro-integrator/docs/references/connectors/fhir-connector/fhir-connector-example.md
Fix https://github.com/wso2/docs-ei/issues/1711
=> Add FHIR documentation

en/micro-integrator/docs/use-cases/examples/endpoint_examples/using-websocket-endpoints.md
> $subject. Resolves #818
- https://github.com/wso2/docs-ei/pull/2623
- https://github.com/wso2/docs-ei/pull/2624
=> Update 'Using a WebSocket Endpoint' example

en/micro-integrator/docs/references/connectors/fhir-connector/fhir-connector-example.md
Fix https://github.com/wso2/docs-ei/issues/1711
=> Add fhir documentation fix for message builder

en/micro-integrator/docs/use-cases/tutorials/using-templates.md
Fixes #1848
Even though the issue is reported for 7.1.0, it's already updated in 7.1.0, and the latest.
This PR will update the 7.0.0 docs
=> [7.0.0] Update Reusing Mediation Sequences tutorial

en/micro-integrator/docs/develop/create-docker-project.md, en/micro-integrator/docs/develop/create-kubernetes-project.md, en/micro-integrator/docs/setup/deployment/k8s-samples/content-based-routing.md, en/micro-integrator/docs/setup/deployment/k8s-samples/hello-world.md, en/micro-integrator/docs/setup/deployment/k8s-samples/jms-sender-receiver.md
=> [Master]Docker image error

en/micro-integrator/docs/develop/creating-unit-test-suite.md
=> Add note about scheduled tasks in Creating Unit Test Suite section

en/micro-integrator/docs/setup/user_stores/setting_up_ro_ldap.md
Resolves https://github.com/wso2/docs-ei/issues/1998
=> [7.0.0] Add wum updated config for user store

en/micro-integrator/docs/use-cases/examples/rest_api_examples/setting-query-params-outgoing-messages.md, en/micro-integrator/docs/use-cases/examples/rest_api_examples/using-post-with-query-param.md
Fixes https://github.com/wso2/docs-ei/issues/1573
=> [7.1.0]Reading query params

en/micro-integrator/docs/develop/creating-unit-test-suite.md
=> [7.1.0] Add note about scheduled tasks in Creating Unit Test Suite section

en/micro-integrator/docs/develop/creating-unit-test-suite.md
=> [7.0.0] Add note about scheduled tasks in Creating Unit Test Suite section

en/micro-integrator/docs/use-cases/examples/data_integration/mongo-data-service.md
Updated the Mongodb example.
The idea is to make it clear that we are only trying out one scenario (GET request) from the data service.
Fixes https://github.com/wso2/docs-ei/issues/2137
=> (7.1.0 branch) Mongo datasource

en/micro-integrator/docs/use-cases/examples/data_integration/mongo-data-service.md, en/micro-integrator/mkdocs.yml
adding the mongodb example to master branch
=> (master branch) Mongo datasource

en/streaming-integrator/docs/admin/viewing-dashboards.md
=> Add sub headings in the "Monitoring ETL Flows with Grafana" page

en/micro-integrator/docs/references/mediators/property-Mediator.md
Related isssue https://github.com/wso2/docs-ei/issues/1858
=> Refactor property mediator docs

en/micro-integrator/docs/references/connectors/gmail-connector/configuring-gmail-api.md, en/micro-integrator/docs/references/connectors/gmail-connector/gmail-connector-overview.md, en/micro-integrator/docs/references/connectors/google-spreadsheet-connector/get-credentials-for-google-spreadsheet.md, en/micro-integrator/docs/references/connectors/google-spreadsheet-connector/google-spreadsheet-overview.md, en/micro-integrator/mkdocs.yml
Related to #1865
Porting https://github.com/wso2/docs-ei/pull/2660
=> Adding setup docs for Gmail and Sheets to the navigation

en/micro-integrator/docs/use-cases/examples/template_examples/using-endpoint-templates.md
> Resolves: https://github.com/wso2/docs-ei/issues/634 …
=> Adding working sample

en/micro-integrator/docs/references/connectors/gmail-connector/configuring-gmail-api.md, en/micro-integrator/docs/references/connectors/gmail-connector/gmail-connector-overview.md, en/micro-integrator/docs/references/connectors/google-spreadsheet-connector/get-credentials-for-google-spreadsheet.md, en/micro-integrator/docs/references/connectors/google-spreadsheet-connector/google-spreadsheet-overview.md, en/micro-integrator/mkdocs.yml
Related to #1865
Porting #2660
=> [7.0.0] Adding setup docs for Gmail and Sheets to the navigation

en/micro-integrator/docs/references/mediators/transaction-Mediator.md
Fixes https://github.com/wso2/docs-ei/issues/2300
=> Removed un supported actions from Transaction Mediator

en/micro-integrator/docs/references/mediators/transaction-Mediator.md
Fixes https://github.com/wso2/docs-ei/issues/2300
=> Removed un supported actions from Transaction Mediator 

en/micro-integrator/docs/references/mediators/call-Mediator.md
> Resolves: https://github.com/wso2/docs-ei/issues/2033 …
=> Add a note on call mediator

en/micro-integrator/docs/references/synapse-properties/endpoint-properties.md
Fix issues in the "Endpoint error handling properties" section. 
Resolves https://github.com/wso2/docs-ei/issues/2478
=> Fix endpoint error handling properties

en/micro-integrator/docs/administer-and-observe/using-the-command-line-interface.md, en/micro-integrator/docs/administer-and-observe/working-with-monitoring-dashboard.md, en/micro-integrator/docs/develop/creating-artifacts/creating-an-api.md, en/micro-integrator/docs/develop/installing-WSO2-Integration-Studio.md, en/micro-integrator/docs/setup/installation/install_in_vm_binary.md, en/micro-integrator/docs/setup/installation/install_in_vm_installer.md
Add videos to docs. Fixes https://github.com/wso2/docs-ei/issues/2469
=> Add videos

en/micro-integrator/docs/setup/transport_configurations/multi-https-transport.md
Add temporary note until https://github.com/wso2/micro-integrator/issues/2034 resolve
=> add note for multi-https transport

en/micro-integrator/docs/setup/transport_configurations/multi-https-transport.md
=> remove duplicate content

en/micro-integrator/docs/administer-and-observe/working-with-management-api.md, en/micro-integrator/docs/references/config-catalog.md, en/micro-integrator/docs/setup/install_and_setup_overview.md, en/micro-integrator/docs/setup/security/encrypting_plain_text.md, en/micro-integrator/docs/setup/security/using-hashicorp-secrets.md, en/micro-integrator/mkdocs.yml, en/micro-integrator/tools/config-catalog-generator/data/_external-vault.toml, en/micro-integrator/tools/config-catalog-generator/data/configs.json, en/micro-integrator/tools/config-catalog-generator/dist/config-catalog.md
Hashicorp secure vault
Fixes https://github.com/wso2/docs-ei/issues/2467
=> (7.1.0 branch) hashicorp documentation

en/micro-integrator/docs/administer-and-observe/logs/configuring_log4j_properties.md
merging custom log appender docs to master.
=> (master branch) custom log appender

en/micro-integrator/docs/develop/advanced-development/applying-security-to-a-proxy-service.md
Added WIP note to 'Applying Security to Proxy Service' doc.
=> (7.1.0 branch) Added WIP banner to doc on Applying Security to Proxy Service

en/streaming-integrator/docs/admin/configuring-Database-and-File-System-State-Persistence.md, en/streaming-integrator/docs/admin/viewing-overall-statistics.md, en/streaming-integrator/docs/admin/viewing-server-statistics.md, en/streaming-integrator/docs/develop/http-status-codes.md, en/streaming-integrator/docs/ref/performance-analysis-results.md, en/streaming-integrator/docs/setup/configuring-data-sources.md, en/streaming-integrator/docs/setup/deployment-guide.md
=> Add information about Grafana dashboards available to monitor Siddhi statistics

en/micro-integrator/docs/references/mediators/payloadFactory-Mediator.md
Update payload factory documentation on the template type attribute.
Related PR: https://github.com/wso2-support/wso2-synapse/pull/990
=> Update documentation on FreeMarker template support

en/micro-integrator/docs/references/mediators/payloadFactory-Mediator.md
Reverts wso2/docs-ei#2690
We will merge this once Integration Studio 8.0.0 is released. This is because the tooling support for this feature is only available through Integration Studio 8.0.0.
=> Revert "Update documentation on FreeMarker template support"

en/micro-integrator/docs/setup/observability/setting-up-minimum-basic-observability-deployment.md
Starting up information for MI is missing from docs. This PR adds that information.
=> Add missing information to setting up micro integrator section

en/micro-integrator/docs/setup/installation/install_prerequisites.md
This PR adds Oracle JDK 11 under tested JDK list.
=> Add Oracle JDK 11 under tested JDKs

en/micro-integrator/docs/setup/performance_tuning/jms_transport_tuning.md
fixed EIINTERNAL-673 by adding a note in [1] as shown in the image below.
[1] https://ei.docs.wso2.com/en/7.1.0/micro-integrator/setup/performance_tuning/jms_transport_tuning/#using-the-jmsproperties-file
=> fixes EIINTERNAL-673

en/micro-integrator/docs/overview/introduction.md
Fixed a typo.
Changed "allow" to "allows"
=> Fixed a typo

en/micro-integrator/docs/setup/performance_tuning/jms_transport_tuning.md
fix for EIINTERNAL-673 based on review comments
=> fix for EIINTERNAL-673 based on review comments

en/micro-integrator/docs/setup/performance_tuning/jms_transport_tuning.md
Define connection between max and core values EIINTERNAL-673
=> Define connection between max and core values EIINTERNAL-673

en/micro-integrator/docs/references/connectors/ceridiandayforce-connector/configuration/orgUnits.md, en/micro-integrator/docs/references/connectors/ceridiandayforce-connector/employee.md
=> Add newly introduced Dayforce connector parameters to doc

en/micro-integrator/docs/references/connectors/ceridiandayforce-connector/configuration/orgUnits.md, en/micro-integrator/docs/references/connectors/ceridiandayforce-connector/employee.md
=> Add newly introduced dayforce connector parameters to docs

en/micro-integrator/docs/references/connectors/mongodb-connector/mongodb-connector-config.md
Fixed broken JSON code in mongodb-connector-config.md.
=> Updated json code in mongodb config

en/micro-integrator/docs/references/connectors/mongodb-connector/mongodb-connector-overview.md
=> updated compatibility info

en/micro-integrator/docs/setup/installation/install_prerequisites.md
=> RHEL compatibility updated

en/micro-integrator/docs/setup/performance_tuning/jms_transport_tuning.md
Updated steps in the using the jms.properties file section.
fixes EIINTERNAL-673
=> Updated steps in the using the jms.properties file section

en/micro-integrator/docs/setup/performance_tuning/jms_transport_tuning.md
updated based on review feedback
Related to https://github.com/wso2/docs-ei/pull/2723
fixes EIINTERNAL-673
=> updated based on review feedback

en/micro-integrator/docs/references/connectors/jira-connector/jira-connector-config.md, en/micro-integrator/docs/references/connectors/jira-connector/jira-connector-example.md, en/micro-integrator/docs/references/connectors/jira-connector/jira-connector-overview.md, en/micro-integrator/mkdocs.yml
WIP docs for the JIRA connector
=> WIP docs for the Jira connector

en/streaming-integrator/docs/setup/installing-si-as-a-linux-service.md, en/streaming-integrator/mkdocs.yml
=> Add the "Installing as a Linux Service" page

en/streaming-integrator/docs/setup/deploying-si-as-an-active-active-deployment.md, en/streaming-integrator/docs/setup/installing-si-as-a-linux-service.md
=> Update note in `Active-Active Deployment` page

en/micro-integrator/docs/references/connectors/jira-connector/jira-connector-config.md
Refining the descriptions of the Jira connector parameters.
=> (master branch) Jira connector configs updated

en/streaming-integrator/docs/examples/running-si-with-docker-and-kubernetes.md, en/streaming-integrator/docs/setup/installing-si-using-kubernetes.md
- Ran FindSecurityBugs plugin and verified report? yes/no
=> Correct errors in Running the Streaming Integrator in Containerized Environments tutorial

en/streaming-integrator/docs/setup/installing-si-using-kubernetes.md
This PR fix a typo in K8s setup documentation.
=> Fix typo in resource path

en/micro-integrator/docs/references/connectors/jira-connector/jira-connector-config.md, en/micro-integrator/docs/references/connectors/jira-connector/jira-connector-example.md, en/micro-integrator/docs/references/connectors/jira-connector/jira-connector-overview.md
Jira connector - remove WIP banner
=> Jira connect WIP banner removed

en/micro-integrator/docs/references/connectors/jira-connector/jira-connector-overview.md
=> Jira connector - typo

en/streaming-integrator/docs/examples/performing-real-time-etl-with-mysql.md, en/streaming-integrator/docs/quick-start-guide/getting-started/monitor-statistics.md, en/streaming-integrator/docs/setup/installing-si-using-kubernetes.md
=> Correct broken link

en/micro-integrator/docs/references/connectors/jira-connector/jira-connector-overview.md
Merging [1] to master.
[1] https://github.com/wso2/docs-ei/pull/2742/files
=> fixing typo

en/micro-integrator/docs/references/connectors/file-connector/file-connector-config.md
=> formatting updated

en/micro-integrator/docs/references/mediators/property-Mediator.md, en/micro-integrator/docs/references/mediators/property-reference/accessing-properties-with-xpath.md
This PR updates the Property Mediator documentation with the file scope support.
Related PR: https://github.com/wso2-support/wso2-synapse/pull/1154
=> Update property mediator doc on file scope support

en/streaming-integrator/mkdocs.yml
=> Add a new link to the Installing Siddhi Extensions section

en/micro-integrator/docs/setup/transport_configurations/multi-https-transport.md
When enabling the dynamic SSL profiles, the "org.apache.synapse.transport.passthru.PassThroughHttpMultiSSLListener" needs to be configured as the transport receiver in the axis2.xml after disabling the default transport receiver"org.apache.synapse.transport.passthru.PassThroughHttpSSLListener". 
Also, It is recommended to configure the hostname as the server when configuring custom SSL profiles. If an IP address is required to be configured as the server, the IP address needs to be mapped to a hostname in the Host file, and the hostname can be provided as the server.
Fixes: https://github.com/wso2/docs-ei/issues/2757
Related issue: https://github.com/wso2/micro-integrator/issues/2034
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in …
=> Add missing information on how to enable dynamic SSL profiles correctly

en/micro-integrator/docs/setup/observability/setting-up-cloud-native-observability-in-kubernetes.md, en/micro-integrator/docs/setup/observability/setting-up-minimum-basic-observability-deployment.md
=> Jaeger tracing documentation updates

en/streaming-integrator/docs/quick-start-guide/getting-started/monitor-statistics.md
=> Update related to growth of the WSO2MetricsDB

en/home-page/theme/material/partials/header.html, en/micro-integrator/theme/material/partials/header.html, en/streaming-integrator/theme/material/partials/header.html
Add banner redirecting EI docs to API-M latest docs
=> Add banner redirecting EI docs to API-M latest docs

en/micro-integrator/docs/references/connectors/file-connector/file-connector-config.md
=> Adding the private key configs

en/home-page/docs/assets/js/theme.js, en/micro-integrator/docs/assets/js/theme.js, en/streaming-integrator/docs/assets/js/theme.js
> remove js sort on string versions to prevent the incorrect ordering of the product version dropdown
=> remove js sort on string versions

en/micro-integrator/docs/setup/transport_configurations/multi-https-transport.md
=> Add  xmlns:svns namespace in the parameter section

en/micro-integrator/docs/references/security/security-implementation.md
=> Add missing configuration files for Kerberos Token-based Security

en/micro-integrator/docs/administer-and-observe/working-with-management-api.md, en/micro-integrator/docs/develop/deploy-artifacts.md
Add documentation for maven car deployment plugin and newly added management apis
Add more context
=> Add documentation for maven car deploy plugin and new apis

en/micro-integrator/docs/develop/deploy-artifacts.md
=> Remove unwanted content

en/streaming-integrator/docs/develop/siddhi-Application-Overview.md
Add persisted aggregation docs 
=> Add persisted aggregation documentation

en/home-page/theme/material/partials/footer.html
fixes https://github.com/wso2/docs-ei/issues/2805
=> fixes https://github.com/wso2/docs-ei/issues/2805

en/micro-integrator/docs/administer-and-observe/logs/masking_sensitive_info_in_logs.md
- Sync PR for #2496 
- Fix for E-986
=> Log Masking Documentation update

en/micro-integrator/docs/references/mediators/property-reference/accessing-properties-with-xpath.md
Adds documentation for the update shipping https://github.com/wso2/micro-integrator/issues/2332
=> Add documentation on file.properties auto reload

en/home-page/docs/assets/css/theme.css, en/home-page/theme/material/partials/footer.html, en/micro-integrator/docs/assets/css/theme.css, en/micro-integrator/theme/material/partials/footer.html, en/streaming-integrator/docs/assets/css/theme.css, en/streaming-integrator/theme/material/partials/footer.html
fixes https://github.com/wso2/docs-apim/issues/4231 in the EI 7.1.0 docs
=> fixes https://github.com/wso2/docs-apim/issues/4231

en/micro-integrator/docs/references/connectors/file-connector/file-connector-config.md
This Pr adds the following information.
1. Add missing parameter "responseFormat" in listFiles operation
2. Add new parameter "filePattern" in move operation
> Brief description of the new feature or bug fix as it …
=> Update file connector issues

en/micro-integrator/docs/setup/installation/install_prerequisites.md
fixes https://github.com/wso2/docs-apim/issues/4384
=> fixes https://github.com/wso2/docs-apim/issues/4384

en/micro-integrator/docs/references/connectors/file-connector/file-connector-config.md
=> Introduce new params for delete and isFileExist operations

en/micro-integrator/docs/references/connectors/ldap-connector/ldap-server-configuration.md
=> LDAP Connector Search for >= JSON format

en/micro-integrator/docs/references/config-catalog.md, en/micro-integrator/docs/setup/security/using-hashicorp-secrets.md, en/micro-integrator/tools/config-catalog-generator/data/_external-vault.toml, en/micro-integrator/tools/config-catalog-generator/dist/config-catalog.md, en/micro-integrator/tools/config-catalog-generator/node_modules/glob-parent/index.js, en/micro-integrator/tools/config-catalog-generator/node_modules/glob-parent/package.json, en/micro-integrator/tools/config-catalog-generator/package-lock.json
Update Config catalog for E-1181
=> Supporting LDAP authentication for Hashicorp vault

en/micro-integrator/docs/references/connectors/microsoft-azure-storage-connector/microsoft-azure-storage-connector-example.md, en/micro-integrator/docs/references/connectors/microsoft-azure-storage-connector/microsoft-azure-storage-reference.md
The new parameter `defaultEndpointsProtocol` added to the Azure Storage connector with the PR https://github.com/wso2-extensions/esb-connector-msazurestorage/pull/8. This Documentation change will contain the instructions to configure it with the custom protocol.
=> Update Azure storage connector documentation for 1.0.1

en/micro-integrator/docs/references/connectors/redis-connector/2.3.x/redis-connector-reference.md, en/micro-integrator/mkdocs.yml
Adding Redis connector 2.3.0 related docs.
- https://github.com/wso2-extensions/esb-connector-redis/pull/34
- https://github.com/wso2-extensions/esb-connector-redis/issues/32
=> Add Redis connector 2.3.0 docs

en/micro-integrator/docs/administer-and-observe/working-with-management-api.md
Add doc update on https://github.com/wso2/micro-integrator/issues/2388
NOTE: Do not merge this until the update WSO2-CARBON-PATCH-4.5.0-0776 is released.
=> [DO NOT MERGE]Update management api documentation

en/streaming-integrator/docs/develop/siddhi-Application-Overview.md
Add persisted aggregation documentation
=> Add persisted aggregation doc changes

en/streaming-integrator/docs/guides/handling-errors.md
Add documentation change for the fix
=> Add documentation changes for oracle query fix

en/micro-integrator/docs/use-cases/examples/jms_examples/producing-jms.md
=> Change jms:transport.jms.ConnectionFactory name - Producing JMS Messages doc

en/micro-integrator/docs/use-cases/examples/file-processing/Accessing_Windows_Share_Using_VFS_Transport.md
=> Add SMB-2 support for EI 

en/micro-integrator/docs/references/mediators/property-reference/axis2-properties.md
=> Fix table heading

en/micro-integrator/docs/setup/security/encrypting_plain_text.md
Update the documentation with Starting server as a background job section
=> Update encrypting_plain_text documentation

en/micro-integrator/docs/administer-and-observe/working-with-management-api.md
> Add data-source resource to management api.
> This feature was added to MI-1.2.0.
=> Add data-source resource to management api.

en/micro-integrator/docs/setup/deployment/deploying_wso2_ei.md
=> Add HeartBeat Related Info For MI Docs

en/micro-integrator/docs/references/config-catalog.md, en/micro-integrator/tools/config-catalog-generator/data/_external-vault.toml, en/micro-integrator/tools/config-catalog-generator/dist/config-catalog.md
Follow up with https://github.com/wso2/docs-ei/pull/2833
=> Port Hashicorp Fixes to MI 4.0.0

en/micro-integrator/docs/references/mediators/payloadFactory-Mediator.md
Reverts wso2/docs-ei#2698
Applying the documentation changes since Integration Studion 8.0.0 has been released.
=> Revert "Revert "Update documentation on FreeMarker template support""

en/micro-integrator/docs/use-cases/examples/data_integration/json-with-data-service.md
$subject
Fixes https://github.com/wso2/micro-integrator/issues/1522
=> [7.1.0] Add note on DSS Json template guidelines

en/micro-integrator/docs/setup/deployment/migrating-from-esb-5.x.x.md
=> fixes E-1713

en/micro-integrator/docs/references/mediators/data-Mapper-Mediator.md
- fixes E-1722
The following two notes have been added.
=> fixes E-1722

en/micro-integrator/docs/references/mediators/validate-Mediator.md
=> fixes Git A-132

en/micro-integrator/docs/references/connectors/salesforce-connectors/sf-rest-connector-config.md
Update Salesforce REST connector docs with `getReport` operation which was added by https://github.com/wso2-extensions/esb-connector-salesforcerest/pull/55
=> Update Salesforce REST connector docs with getReport operation

en/micro-integrator/docs/setup/deployment/health_check.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/372
=> [Sync 7.0.0] Update health_check.md

en/micro-integrator/docs/setup/deployment/health_check.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/372
=> [Sync 7.1.0] Update health_check.md

en/micro-integrator/docs/setup/deployment/health_check.md
=> Revert "[Sync 7.0.0] Update health_check.md"

en/streaming-integrator/docs/setup/upgrading-wso2-ei.md, en/streaming-integrator/mkdocs.yml
Adds new migration page for SI and removes old one.
=> Add SI migration content

en/micro-integrator/docs/references/connectors/kafka-connector/kafka-connector-config.md, en/micro-integrator/docs/references/connectors/kafka-connector/kafka-connector-overview.md
Update Kafka connector docs with the `key` param
https://github.com/wso2-extensions/esb-connector-kafka/pull/69
=> Update kafka connector docs with the 'key' param

en/home-page/docs/assets/css/style.css, en/micro-integrator/docs/assets/css/style.css, en/streaming-integrator/docs/assets/css/style.css
Follow-up with https://github.com/wso2/docs-ei/pull/2940
=> Replace unnecessary font names

en/home-page/docs/index.md
This PR is to update the reference link to Enterprise Integration Patterns on https://ei.docs.wso2.com/en/latest/.
=> Fix broken link on index.md

en/micro-integrator/docs/setup/observability/setting-up-classic-observability-deployment.md
$subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
=> Add datasource configuration section to abalytics docs

en/micro-integrator/docs/references/connectors/csv-module/csv-module-config.md
Related to https://github.com/wso2/micro-integrator/issues/2976, https://github.com/wso2-extensions/mediation-csv-module/pull/14
=> Introduce new parameter to CSV module reference

en/micro-integrator/docs/references/synapse-properties/transport-parameters/vfs-transport-parameters.md
$subject Related to https://github.com/wso2/api-manager/issues/2231
=> [1.1.0] Remove cluster configuration from VFS Listener

en/micro-integrator/docs/references/connectors/ldap-connector/ldap-server-configuration.md
$subject
Related to https://github.com/wso2/product-ei/issues/4598
=> Introduce new parameter to LDAP Connector search

en/micro-integrator/docs/develop/deploy-artifacts.md
This property is added by https://github.com/wso2/maven-tools/pull/88
> Link(s) to product documentation that addresses the …
=> Add docs on serverType property

en/micro-integrator/docs/references/connectors/kafka-connector/kafka-inbound-endpoint-config.md, en/micro-integrator/docs/references/connectors/kafka-connector/kafka-inbound-endpoint-example.md, en/micro-integrator/mkdocs.yml
$subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
=> Add kafka inbound endpoint reference guide

en/micro-integrator/docs/develop/deploy-artifacts.md, en/micro-integrator/docs/references/connectors/kafka-connector/3.0.x/kafka-connector-config.md, en/micro-integrator/docs/references/connectors/kafka-connector/kafka-connector-config.md
The property is added by https://github.com/wso2-extensions/esb-connector-kafka/pull/33/files
> Link(s) to product …
=> Add saslMechanism parameter to Kafka docs

en/micro-integrator/theme/material/partials/header.html
This PR is to update the banner redirecting MI-related content to the latest MI documentation.
Issue reference: https://github.com/wso2/docs-ei/issues/2964
=> [7.1.0] Update the redirection banner

en/micro-integrator/theme/material/partials/header.html
This PR is to update the banner redirecting MI-related content to the latest MI documentation.
Issue reference: https://github.com/wso2/docs-ei/issues/2964
=> [7.0.0] Update the redirection banner

en/home-page/theme/material/partials/header.html
This PR is to update the banner on the homepage redirecting the site to the latest MI documentation.
Issue reference: https://github.com/wso2/docs-ei/issues/2964
=> [7.1.0] Update the redirection banner on homepage

en/home-page/theme/material/partials/header.html
This PR is to update the banner on the homepage redirecting the site to the latest MI documentation.
Issue reference: https://github.com/wso2/docs-ei/issues/2964
=> [7.0.0] Update the redirection banner on homepage

en/micro-integrator/docs/references/connectors/email-connector/email-connector-config.md
$subject
Issue reference: https://github.com/wso2/micro-integrator/issues/3073
=> [7.0.0] Update email connector doc

en/micro-integrator/docs/references/connectors/email-connector/email-connector-config.md
$subject
Issue reference: https://github.com/wso2/micro-integrator/issues/3073
=> [7.1.0] Update email connector doc

en/micro-integrator/theme/material/partials/header.html
=> [7.0.0] Fix banner formatting

en/micro-integrator/theme/material/partials/header.html
=> [7.1.0] Fix banner formatting

en/micro-integrator/docs/references/connectors/amazons3-connector/amazons3-connector-config.md
=> Add new S3 connector sdk version related jars

en/micro-integrator/docs/setup/message_builders_formatters/message-builders-and-formatters.md
This PR is to update the default Content-Type parameter for the requests.
Issue Reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/666
=> [7.1.0] Update the default Content-Type parameter for the requests

en/streaming-integrator/docs/setup/configuring-data-sources.md
=> Add a note about H2 DBs not recommended in production for SI

en/streaming-integrator/docs/setup/configuring-data-sources.md
=> Revert "Add a note about H2 DBs not recommended in production for SI"

en/micro-integrator/mkdocs.yml
=> [7.1.0] Remove the markdown.include extension

en/micro-integrator/mkdocs.yml
=> [7.0.0] Remove the markdown.include extension

en/streaming-integrator/docs/setup/configuring-data-sources.md
=> Revert "Revert "Add a note about H2 DBs not recommended in production for SI""

en/micro-integrator/docs/references/error_handling.md
This PR is to add the error code 601000 to the docs.
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/777
=> [7.1.0] Add error code 601000

en/micro-integrator/docs/references/error_handling.md
$subject
**Issue reference:** https://github.com/wso2-enterprise/wso2-mi-internal/issues/831
=> [7.0.0] Update error_handling.md

en/micro-integrator/docs/references/error_handling.md
$subject
**Issue reference:** https://github.com/wso2-enterprise/wso2-mi-internal/issues/831
=> [7.1.0] Update error_handling.md

en/micro-integrator/docs/references/synapse-properties/endpoint-properties.md
$subject
**Related PR:**
https://github.com/wso2/docs-mi/pull/107
**Issue reference:**
https://github.com/wso2/docs-mi/issues/108
=> [7.1.0] Update the `synapse.timeout_handler_interval` property

en/micro-integrator/docs/develop/customizations/creating-synapse-handlers.md
$subject
**Issue reference:** https://github.com/wso2/docs-mi/issues/258
=> [7.1.0] Update toml config in Synapse Handlers

en/micro-integrator/docs/references/connectors/amazonlambda-connector/amazonlambda-connector-config.md
$subject
**Issue reference:** https://github.com/wso2-enterprise/wso2-mi-internal/issues/721
=> [7.1.0] Update amazonlambda-connector-config.md

en/micro-integrator/docs/references/connectors/amazonlambda-connector/amazonlambda-connector-config.md
$subject
**Issue reference:** https://github.com/wso2-enterprise/wso2-mi-internal/issues/721
=> [7.0.0] Update amazonlambda-connector-config.md

en/micro-integrator/docs/references/connectors/file-connector/file-connector-config.md, en/micro-integrator/docs/references/synapse-properties/transport-parameters/vfs-transport-parameters.md
$subject
This will fix https://github.com/wso2/docs-mi/issues/116.
=> [7.1.0] Add note for username and password

en/micro-integrator/docs/references/best-Practices.md
=> Replaced WUM with U2.

en/micro-integrator/docs/overview/introduction.md
=> fix typo in introduction.md

en/micro-integrator/docs/develop/installing-WSO2-Integration-Studio.md
updated distributions link to navigate to the correct location
=> distrubutions link update

en/micro-integrator/docs/references/connectors/amazons3-connector/2.x/amazons3-connector-reference.md
Fixes
- https://github.com/wso2/docs-apim/issues/7159
=> Update Amazon S3 Connector doc

en/micro-integrator/docs/references/connectors/amazons3-connector/amazons3-connector-reference.md
Fixes
- https://github.com/wso2/docs-apim/issues/7159
=> Update Amazon S3 Connector doc 

en/micro-integrator/docs/references/best-Practices.md, en/micro-integrator/docs/references/mediators/aggregate-Mediator.md, en/micro-integrator/docs/references/mediators/clone-Mediator.md, en/micro-integrator/docs/references/mediators/iterate-Mediator.md, en/micro-integrator/docs/references/mediators/store-Mediator.md
This PR updates the old EIP references to direct to the updated content in the latest MI documentation.
=> [7.1.0] Update EIP references

en/micro-integrator/docs/references/best-Practices.md, en/micro-integrator/docs/references/mediators/aggregate-Mediator.md, en/micro-integrator/docs/references/mediators/clone-Mediator.md, en/micro-integrator/docs/references/mediators/iterate-Mediator.md, en/micro-integrator/docs/references/mediators/store-Mediator.md
This PR updates the old EIP references to direct to the updated content in the latest MI documentation.
=> [7.0.0] Update EIP references
