wso2/docs-ei

en/streaming-integrator/docs/develop/debugging_siddhi_applications.md

Fix links to images that were defined incorrectly in https://github.com/wso2/docs-ei/pull/313.

Fix images to links in the Debugging Siddhi Applications page.

---

en/micro-integrator/docs/assets/css/theme.css

Adds Show Example text for MI hidden code blocks in the reference section
Before
After

Add Show Example text for MI hidden code blocks

---

en/micro-integrator/docs/references/mediators/header-Mediator.md

JSONPath support was added to header mediator with https://github1.com/wso2/wso2-synapse/pull/1364
This PR updates the docs
Related issue : https://github.com/wso2/product-ei/issues/4349
https://github.com/wso2/wso2-synapse/pull/1364

Update header mediator docs with jsonpath support

---

en/streaming-integrator/docs/examples/working-with-kafka.md

Revamp Kafka tutorial
- Moving Publishing to Kafka section down again.
- Fixing the tutorial outline on the doc site.

Revamp Kafka tutorial

---

en/micro-integrator/docs/administer-and-observe/using-the-command-line-interface.md

cli remote login command not working in windows if the user tries to log by adding username and then enter the password. It does not allow user to add the password. As a workaround in windows, the user can add the user name and the password together with the command as shown below,
mi remote login username password
wso2/micro-integrator#1034

Change cli remote login instructions for windows

---

en/micro-integrator/docs/setup/security/encrypting_plain_text.md

> This PR contains the necessary changes to the encrypting passwords doc. As LOGEVENT appender is not used in MI it is removed from the log4j2.properties file.

Update Encrypting Passwords doc

---

en/micro-integrator/docs/use-cases/tutorials/exposing-several-services-as-a-single-service.md
en/micro-integrator/docs/use-cases/tutorials/file-processing.md
en/micro-integrator/docs/use-cases/tutorials/routing-requests-based-on-message-content.md
en/micro-integrator/docs/use-cases/tutorials/sending-a-simple-message-to-a-datasource.md
en/micro-integrator/docs/use-cases/tutorials/sending-a-simple-message-to-a-service.md
en/micro-integrator/docs/use-cases/tutorials/storing-and-forwarding-messages.md
en/micro-integrator/docs/use-cases/tutorials/transforming-message-content.md
en/micro-integrator/docs/use-cases/tutorials/using-inbound-endpoints.md
en/micro-integrator/docs/use-cases/tutorials/using-scheduled-tasks.md
en/micro-integrator/docs/use-cases/tutorials/using-templates.md
en/micro-integrator/docs/use-cases/tutorials/using-the-gmail-connector.md

Tutorial workspace mentions that the Integration Studio should be extracted which is not the case for MacOS.

Update tutorial workspace setup documentation

---

en/micro-integrator/docs/setup/brokers/configure-with-ActiveMQ.md

> Corrected the initial_naming_factory parameter value for ActiveMQ classic instead of ActiveMQ Artemis

Update the initial_naming_factory parameter for ActiveMQ classic

---

en/streaming-integrator/docs/setup/installing-si-in-vm.md

This PR fixes a startup script filename in the Streaming Integrator.

Fix startup script filename in SI

---

en/home-page/mkdocs.yml
en/micro-integrator/mkdocs.yml
en/streaming-integrator/mkdocs.yml

When clicking on the "WSO2" logo icon in the header, the site navigates to the `index.md` of the relevant section, not the root level landing page. This PR fixes that issue by redirecting the site to the root level landing page.

Fix header redirection issue

---

en/micro-integrator/docs/develop/using-wire-logs.md

The wire logs can be enabled using the MI CLI by changing the log level of a logger.
For Example: `mi log-level update synapse-transport-http-wire DEBUG` command can be used to update the log level of synapse-transport-http-wire logger to DEBUG
```
logger.synapse-transport-http-wire.name=org.apache.synapse.transport.http.wire
logger.synapse-transport-http-wire.level=DEBUG
```

Update using-wire-logs documentation

---

en/micro-integrator/docs/develop/hot-deployment.md
en/micro-integrator/docs/references/config-catalog.md

This PR will add the necessary documentation to cover the below points about hot deployment in Micro Integrator.
- What is hot deployment
- When to use it
- When not to use it
- How to enable it

Add docs for hot deployment

---

en/micro-integrator/docs/setup/configuring_proxy_servers.md

This PR fixes configuration parameters URLs "Working with Proxy Servers" page.

Fix configuration parameters URLs

---

en/micro-integrator/docs/setup/configuring_proxy_servers.md

This PR fixes the "configuration parameters" link in the "Working with Proxy Servers" page in MI documentation.

Fix links in Working with Proxy Servers page

---

en/micro-integrator/docs/use-cases/examples/routing_examples/routing_based_on_payloads.md

Correcting a value in the given payload. The payload of the second example should contain the symbol `MSFT`.
Doc: https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/routing_examples/splitting_aggregating_messages/
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/844

Update payload based rounting example

---

en/micro-integrator/docs/use-cases/examples/protocol-switching/switching_from_FTP_listener_to_mail_sender.md

Correcting the synapse configuration.
Doc link: https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/protocol-switching/switching_from_FTP_listener_to_mail_sender/
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/848

Correcting ftp-mail example

---

en/micro-integrator/docs/use-cases/examples/protocol-switching/switching_from_HTTP_to_FIX.md

Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/848

Fixing typos in http-fix example

---

en/micro-integrator/docs/use-cases/examples/rest_api_examples/using-post-with-no-body.md

Changing the synape configuration to send the request to tcpmon and tcpmon to back-end.

Correct restapi empty post example

---

en/micro-integrator/docs/use-cases/examples/endpoint_examples/using-failover-endpoints.md

1. In the first synapse configuration, add a dummy port to the address. This is because windows send an HTML reply with "Not found server" message when connecting to an invalid address without a port.
Then the MI does not pick the correct error code.
2. In the 2nd synapse config, changed the error code as it is the one returned and needed to capture to break the loop

Fix example failover endpoint

---

en/micro-integrator/docs/use-cases/examples/endpoint_examples/using-address-endpoints.md

Removing the outsequence as insequence contains a respond mediator

Fix example address endpoint

---

en/micro-integrator/docs/use-cases/examples/registry_examples/local-registry-entries.md

1. Removed `definitions` related details as it is not used.
2. Updated some of the content following the doc from [EI-6.6.0](https://docs.wso2.com/display/EI660/Sample+14%3A+Using+Sequences+and+Endpoints+as+Local+Registry+Items)
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/868

Update example- sequence as local entry

---

en/micro-integrator/docs/setup/brokers/configure-with-ActiveMQ.md
en/micro-integrator/docs/setup/installation/run_in_docker.md

```
[[transport.jms.listener]]
name = "myQueueListener"
.
.
.
```
When configuring the proxy service (JMS listener), it is a must to add the following connection factory with the name of the already defined connection factory in the deployment.toml file.
```
<parameter name="transport.jms.ConnectionFactory">myQueueListener</parameter>
```
Otherwise, the listener proxy will not work unless we put the JMS connection factory name as "default" in the deployment.toml file.
```
[[transport.jms.listener]]
name = "default"
.
.
.
```

Update ActiveMQ configuration doc

---

en/micro-integrator/docs/use-cases/examples/scheduled-tasks/task-scheduling-simple-trigger.md

1.  Add soap format to avoid `soapAction` changing to `Action` when sending the request
2.  Removed a property from the log that reads an non-existing element in the response
3.  Changed the expression of log properties to match the response

Fix example task scheduled - simple trigger

---

en/micro-integrator/docs/use-cases/examples/rest_api_examples/introduction-rest-api.md

Adding a missing REST call to the restAPI introduction example.

Improve RestAPI example

---

en/micro-integrator/docs/use-cases/examples/rest_api_examples/securing-rest-apis.md

Include details on how the credentials in the header are formed.

Adding missing details to secure restAPI example

---

en/micro-integrator/docs/use-cases/examples/rest_api_examples/using-post-with-query-param.md

Changing the synape configuration to send the request to tcpmon and tcpmon to back-end.

Fix RestApi post with params example

---

en/micro-integrator/docs/use-cases/examples/endpoint_examples/using-websocket-endpoints.md

1. Fixed an issue in synapse config
2. Add additional details in command execution as windows has different syntax

Fix example websocket endpoint

---

en/micro-integrator/docs/use-cases/examples/endpoint_examples/using-wsdl-endpoints.md

Add a new entry to the WSDL file as the existing one are cannot be found when running. Changing the synapse configurations and others accordingly.
Related PR (Adding a new port in the WSDL file): https://github.com/wso2-docs/WSO2_EI/pull/68

Fix example wsdl endpoint

---

en/micro-integrator/docs/use-cases/examples/endpoint_examples/endpoint-error-handling.md

1.  Add a dummy port so that windows does not return 404 HTML request instead of an 10503 error.
2.  Change the synapse configuration of the 2nd example to a rest API as it is explained.

Fix example endpoint error handling

---

en/micro-integrator/docs/use-cases/examples/endpoint_examples/using-loadbalancing-endpoints.md

1. Fixed few issues in synapse configuration
2. Since clients in EI 6.6.0 are not available in the MI, a novel approach is suggested to send requests to 3 different endpoints and view results. In this case, `tcpmon` is used. It listens in 3 different ports while redirecting requests to the same endpoint. But the MI sees them as 3 different endpoints.

Fix example endpoint load balance

---

en/micro-integrator/docs/use-cases/examples/transport_examples/fix-transport-examples.md

1. Remove sample configuration details and point them to [[1](https://ei.docs.wso2.com/en/next/micro-integrator/setup/transport_configurations/configuring-transports/#configuring-the-fix-transport)] similar to the example [[2](https://ei.docs.wso2.com/en/next/micro-integrator/use-cases/examples/protocol-switching/switching_from_FIX_to_HTTP/)].
2. Add missing namespace to the synapse configuration.
[1] https://ei.docs.wso2.com/en/next/micro-integrator/setup/transport_configurations/configuring-transports/#configuring-the-fix-transport
[2] https://ei.docs.wso2.com/en/next/micro-integrator/use-cases/examples/protocol-switching/switching_from_FIX_to_HTTP/
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/878

Fix example transport FIX

---

en/micro-integrator/docs/use-cases/examples/scheduled-tasks/injecting-messages-to-rest-endpoint.md

1.  Removing details on setting up a back-end as this example does not use a back-end.
2.  Correcting the log.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/865

Improving Inject Msg to RestFul example

---

en/micro-integrator/docs/setup/message_builders_formatters/message-builders-and-formatters.md

$subject
Whatever the content-type that we put under [custom_message_builders] or [custom_message_formatters] should be the ones that do not have a default message formatter or builder specified in axis2.xml (i.e. templated through axis2.xml.j2). [Here](https://github.com/wso2/micro-integrator/issues/1347#issuecomment-611947999) is a reference to the summary of the existing message formatters and builders templated in axis2.xml.j2 as per the date of this PR.

Update Custom message formatter sample

---

en/micro-integrator/mkdocs.yml

sending this erroneous PR that should fail the doc build.
Ideally, this commit should not be pushed to the live site, when the build fails. Hence , the doc site should remain active.

testing the doc build

---

en/micro-integrator/docs/develop/creating-projects.md

Fix typo, poject -> project
https://ei.docs.wso2.com/en/latest/micro-integrator/develop/creating-projects/#composite-application-project

Fix project typo in Composite Application Project section.

---

en/micro-integrator/docs/setup/configuring_proxy_servers.md

Remove unwanted v character in 'need tovconfigure'
https://ei.docs.wso2.com/en/7.1.0/micro-integrator/setup/configuring_proxy_servers/#configuring-proxy-profiles-in-wso2-micro-integrator

Fix typo, remove unwanted letter in configuring proxy profiles section.

---

en/micro-integrator/docs/setup/user_stores/setting_up_a_userstore.md

Add information related to default WSO2CarbonDB data source in JDBC Userstore

Add information related to default WSO2CarbonDB data source in JDBC Userstore

---

en/micro-integrator/docs/administer-and-observe/observability.md

Fix typo,  anlyzed -> analyzed, in Monitoring Message Round Trip section.
https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/observability/

Fix typo in Monitoring Message Round Trip section.

---

en/micro-integrator/docs/administer-and-observe/jmx_monitoring.md

Info block style was not being applied -> 'explained above. !!! Info If you are'. 
Added blank line to ensure it is applied.
https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/jmx_monitoring/#starting-jconsole

Add blank line to ensure info block style is applied in Starting JConsole section.

---

en/micro-integrator/docs/administer-and-observe/logs/managing_log_growth.md

Remove white space - "log4j2- based" -> "log4j2-based"
https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/logs/managing_log_growth/#managing-the-growth-of-carbon-logs

Remove white space from Managing the growth of Carbon logs section.

---

en/micro-integrator/docs/administer-and-observe/monitoring_with_prometheus.md

Update broken link 'http://prometheus%202' to 'https://prometheus.io/docs/introduction/overview/'
https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/monitoring_with_prometheus/

Fix Prometheus documentation link.

---

en/micro-integrator/docs/references/mediators/aggregate-Mediator.md
en/micro-integrator/mkdocs.yml

Align nav item 'Aggregate Mediators' -> 'Aggregate Mediator' with page title 'Aggregate Mediator'
Remove duplicated text - 'were split by the _split by the_ '
https://ei.docs.wso2.com/en/latest/micro-integrator/references/mediators/aggregate-Mediator/

Align nav item with page title. Remove duplicated text in description.

---

en/micro-integrator/docs/setup/deployment/k8s-pipeline/adding-test-cases.md
en/micro-integrator/docs/setup/deployment/k8s-pipeline/deploy-your-own-artifact.md
en/micro-integrator/docs/setup/deployment/k8s-pipeline/modifying-product-configurations.md
en/micro-integrator/docs/setup/deployment/k8s-pipeline/pipeline-quick-start-guide.md
en/micro-integrator/mkdocs.yml

> The purpose of changing the Quick start guide name was because the MI documentation itself comprised of its QSG therefore to alleviate any confusion this action was taken
> By changing the pipeline QSG to be renamed to 'Pipeline Quick start guide' there won't be any confusion for the user when searched for it in total search in the site and it brings clarity when searched through the browser.

Change File name and Menu name to 'Pipeline Quick Start Guide'

---

en/micro-integrator/docs/administer-and-observe/observability-overview.md

Prometheus doc is no longer available in 7.1.0 (https://github.com/wso2/docs-ei/pull/2304). Hence, removing the obsolete link.

Remove Prometheus obsolete link

---

en/micro-integrator/docs/setup/changing_default_ports.md

Updating the documentation on default ports in the Micro Integrator to better explain the internal offset of 10, which is effective by default.

(7.1.0 branch) documentation on changing default ports

---

en/micro-integrator/docs/references/mediators/property-reference/axis2-properties.md
en/micro-integrator/docs/references/synapse-properties/transport-parameters/hl7-transport-parameters.md
en/micro-integrator/docs/setup/transport_configurations/configuring-transports.md
en/micro-integrator/docs/use-cases/examples/hl7-examples/HL7_proxy_service.md
en/micro-integrator/docs/use-cases/examples/hl7-examples/acknowledge_hl7_messages.md
en/micro-integrator/docs/use-cases/examples/hl7-examples/file_transfer_using_hl7.md
en/micro-integrator/mkdocs.yml

HL7 documentation updated:
- HL7 message store docs removed (because the HL7 console, which was previously available in the management console is no longer available.
- Refactored the parameters, examples, and mediator properties.

(7.1.0 branch) HL7 parameters and examples

---

en/micro-integrator/docs/overview/about-this-release-7.1.0.md
en/micro-integrator/docs/setup/deployment/migrating-from-ei-6.x.x.md
en/micro-integrator/docs/setup/deployment/migrating-from-esb-5.x.x.md
en/micro-integrator/docs/setup/transport_configurations/configuring-transports.md

Since the HL7 message store is not supported in the Micro Integrator, updating the docs accordingly.

(7.1.0 branch) HL7 message store related changes

---

en/micro-integrator/mkdocs.yml

Changes the site URL to 'latest' as opposed to saying '7.1.0'. 
This is expected to help SEO.
Same practice is used in APIM docs

(7.1.0 branch) updating site URL to latest

---

en/home-page/mkdocs.yml

The site URLis changed to reflect '7.0.0' instead of latest.
This is expected to improve SEO.

(7.0.0 branch) update site URL of HOME PAGE

---

en/micro-integrator/mkdocs.yml

Changed site URL to 7.0.0 instead of latest.
Expected to improve SEO.

(7.0.0 branch) Update site URL of MI DOCS

---

en/streaming-integrator/mkdocs.yml

changed site URL to 7.0.0 instead of latest.
This is expected to improve SEO.

(7.0.0 branch) update site URL for SI DOCS

---

en/micro-integrator/mkdocs.yml

THe edit url should point to 'master' not '7.2.0'.
There is no branch named '7.2.0'.

(master branch) fixing 'edit url' in the yml

---

en/micro-integrator/docs/setup/security/configuring_keystores.md

Update configuring keystores documentation to reflect the changes done in https://github.com/wso2-support/micro-integrator/pull/39.
We have added support to define keystore file location instead of file name,
```
[keystore.primary]
file_name = "repository/resources/security/wso2carbon.jks"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"
```

Update configuring_keystores documentation

---

en/streaming-integrator/docs/admin/creating-business-rules-templates.md
en/streaming-integrator/docs/ref/rest-api-guide-overview.md

Correct the URL to access Business Rules mentioned in documentation and remove references to obsolete APIs

---

en/streaming-integrator/docs/examples/creating-etl-application-via-tooling.md
en/streaming-integrator/docs/examples/performing-real-time-etl-with-mysql.md
en/streaming-integrator/docs/guides/extracting-data-from-static-sources-in-real-time.md
en/streaming-integrator/docs/quick-start-guide/getting-started/download-install-and-start-si.md
en/streaming-integrator/docs/samples/CDCWithListeningMode.md

> When working with CDC and MySQL, we have to enable binary logging as a pre-requisite. We ask to follow Debezium documentation [1] in order to do this. MySQL query for checking the status of binary logging is slightly different in MySQL 8.0, and this is not mentioned in Debezium documentation. 
This PR adds a note regarding this query, in places where the Debezium documentation is referred.
[1] https://debezium.io/documentation/reference/1.3/connectors/mysql.html

[SI] Add note regarding checking binlog status in MySQL 8 for CDC

---

en/micro-integrator/docs/use-cases/examples/rabbitmq_examples/store-forward-rabbitmq.md

Substituting "message processor" for "message store" as the image below indicates that it is the "message store" that forwards the message to the rabbitMQ. I believe this was a mistake.

Correction on Message store and message processor for guaranteed delivery

---

en/micro-integrator/docs/use-cases/examples/endpoint_examples/using-static-recepient-list-endpoints.md

Currently, this [sample](https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/endpoint_examples/using-static-recepient-list-endpoints/) is not saved in Integration studio. This PR will add a WIP note in the top and will point to the issue.
Fixes https://github.com/wso2/docs-ei/issues/2352

[7.1.0] Add a WIP note for not working sample

---

en/micro-integrator/docs/references/connectors/gmail-connector/configuring-gmail-api.md
en/micro-integrator/docs/references/connectors/gmail-connector/gmail-connector-overview.md
en/micro-integrator/docs/references/connectors/google-spreadsheet-connector/get-credentials-for-google-spreadsheet.md
en/micro-integrator/docs/references/connectors/google-spreadsheet-connector/google-spreadsheet-overview.md
en/micro-integrator/mkdocs.yml

This PR will add the setup docs for Gmail and Sheets API to the side navigation. These docs are necessary for the relevant connector setup.
Related to https://github.com/wso2/docs-ei/issues/1865

[7.1.0] Adding setup docs for Gmail and Sheets to the navigation

---

en/micro-integrator/docs/administer-and-observe/logs/configuring_log4j_properties.md

This PR adds instructions to use custom Log4j2 log appenders with WSO2 Micro Integrator.
Resolves https://github.com/wso2/docs-ei/issues/2260

Add instruction to use Log4j2 custom log appenders

---

en/micro-integrator/docs/setup/performance_tuning/jms_transport_tuning.md

fixes EIINTERNAL-673 by adding a note as shown in the image below in [1].
[1] https://ei.docs.wso2.com/en/7.0.0/micro-integrator/setup/performance_tuning/jms_transport_tuning/#using-the-jmsproperties-file

fixes EIINTERNAL-673

---

en/docs/index.md

Since another EI release is not planned for the present, removing EI 7.2.0 from the versions page.

removed EI 7.2.0 from versions page

---

en/micro-integrator/docs/setup/transport_configurations/multi-https-transport.md

When enabling the dynamic SSL profiles, the "org.apache.synapse.transport.passthru.PassThroughHttpMultiSSLListener" needs to be configured as the transport receiver in the axis2.xml after disabling the default transport receiver"org.apache.synapse.transport.passthru.PassThroughHttpSSLListener".
Also, It is recommended to configure the hostname as the server when configuring custom SSL profiles. If an IP address is required to be configured as the server, the IP address needs to be mapped to a hostname in the Host file, and the hostname can be provided as the server.
Related PRs: https://github.com/wso2/docs-ei/pull/2758

Add missing information on how to enable dynamic SSL profiles correctly

---

en/micro-integrator/docs/references/mediators/call-Mediator.md
en/micro-integrator/docs/references/mediators/property-reference/http-transport-properties.md

This PR updates the documentation for the following fixes,
https://github.com/wso2/wso2-axis2/pull/201, https://github.com/wso2-support/wso2-axis2/pull/173
- The system property **allowEmptyBodyForHttp2xx** can be set to allow receiving response without body for HTTP status code 200, 201, 202 (for blocking calls)
- The property non.error.http.status.codes can be used to configure HTTP status codes that need to be considered as non-error status codes (for blocking calls)
`<property name="non.error.http.status.codes" scope="axis2" value="403" type="STRING"/>`

Update documentation with blocking mode fixes

---

en/micro-integrator/docs/references/mediators/property-reference/http-transport-properties.md

The property non.error.http.status.codes can be used to configure HTTP status codes that need to be considered as non-error status codes (for blocking calls)
`<property name="non.error.http.status.codes" scope="axis2" value="403" type="STRING"/>`
Related PR: https://github.com/wso2/wso2-axis2/pull/201

[Master] Update documentation with non.error.http.status.codes property

---

en/micro-integrator/docs/references/connectors/file-connector/3.x/file-connector-3.x-config.md

Add the document changes related to the new property `setAvoidPermission` which is added to the file connector move operation by https://github.com/wso2-extensions/esb-connector-file/pull/164.

Add option to skip file permission check in the move operation

---

en/micro-integrator/docs/references/connectors/kafka-connector/kafka-connector-config.md

With https://github.com/wso2-extensions/esb-connector-kafka/pull/62, for Kafka connector v3.1.2 and above, when an error occurs the error will get set to the message context. This PR update the docs with the relevant error code.

Update kafka docs with error codes

---

en/micro-integrator/docs/references/connectors/amazons3-connector/amazons3-connector-example.md
en/micro-integrator/docs/references/connectors/amazons3-connector/amazons3-connector-reference.md

With https://github.com/wso2-extensions/esb-connector-amazons3/pull/50 the `getObject` operation of the Amazon S3 connector was improved. This doc adds the related new changes.
- Add a new parameter called `destinationFilePath` to getObject operation to download the file to the local server.
- Set the file content in the GetObjectResponse.

Update Amazon S3 connector docs with 2.0.1 release features

---

en/micro-integrator/docs/references/connectors/kafka-connector/kafka-connector-producer-example.md

Fix https://github.com/wso2/docs-apim/issues/3649
This instruction update should be only for the Kafka version lower than 2.2. The latest version does support the `--bootstrap-server` option. Therefore, a note was added along with the command to specify how to create a topic in Kafka 2.2 and lower versions.

Update kafka connector 2.2 instructions

---

en/micro-integrator/docs/references/connectors/amazonsqs-connector/amazonsqs-connector-config.md
en/micro-integrator/docs/references/connectors/amazonsqs-connector/amazonsqs-connector-overview.md

With https://github.com/wso2-extensions/esb-connector-amazonsqs/pull/25 when the MI/EI server is running in an EC2 instance, the user can set the IAM role for authentication This doc adds the related new changes.
- Update the init configuration docs.

[7.1.0] Update Amazon SQS connector docs with IAM role for authentication

---

en/micro-integrator/docs/references/connectors/amazonsqs-connector/amazonsqs-connector-config.md
en/micro-integrator/docs/references/connectors/amazonsqs-connector/amazonsqs-connector-overview.md

With https://github.com/wso2-extensions/esb-connector-amazonsqs/pull/25 when the MI/EI server is running in an EC2 instance, the user can set the IAM role for authentication This doc adds the related new changes.
- Update the init configuration docs.

[Master] Update Amazon SQS connector docs with IAM role for authentication

---

en/micro-integrator/docs/references/mediators/payloadFactory-Mediator.md

This PR updates the documentation with FreeMarker support.
Back-port https://github.com/wso2/docs-apim/pull/3039, https://github.com/wso2/docs-apim/pull/3305
On top of this documentation is updated with XML to EDI transformation example.
Fixes https://github.com/wso2/micro-integrator/issues/2558
Related PRs: wso2-support/wso2-synapse#990, https://github.com/wso2/docs-ei/pull/2690

[7.1.0] Update payloadFactory-mediator documentation with FreeMarker support

---

en/micro-integrator/docs/references/synapse-properties/transport-parameters/vfs-transport-parameters.md

$subject Related to https://github.com/wso2/api-manager/issues/2231

[1.2.0] - Remove cluster configuration from VFS Listener
